CREATE TABLE IF NOT EXISTS bpm_process_instance (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  flowable_instance_id VARCHAR(150) NOT NULL UNIQUE,
  flowable_definition_id VARCHAR(150) NOT NULL,
  process_code VARCHAR(100) NOT NULL,
  business_type VARCHAR(60) NOT NULL,
  business_id VARCHAR(100),
  business_key VARCHAR(180),
  title VARCHAR(200) NOT NULL,
  starter VARCHAR(64) NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'RUNNING',
  started_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ended_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS bpm_form_definition (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  form_code VARCHAR(100) NOT NULL UNIQUE,
  form_name VARCHAR(150) NOT NULL,
  business_type VARCHAR(60) NOT NULL DEFAULT 'COMMON',
  schema_json TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bpm_task_action (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  flowable_task_id VARCHAR(150) NOT NULL,
  flowable_instance_id VARCHAR(150) NOT NULL,
  action_code VARCHAR(30) NOT NULL,
  actor VARCHAR(64) NOT NULL,
  comment_text VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bpm_process_design (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  process_code VARCHAR(100) NOT NULL UNIQUE,
  process_name VARCHAR(150) NOT NULL,
  description VARCHAR(500),
  category VARCHAR(80),
  process_type VARCHAR(30) NOT NULL DEFAULT 'APPROVAL',
  trigger_type VARCHAR(30) NOT NULL DEFAULT 'MANUAL',
  version INT NOT NULL DEFAULT 1,
  design_json TEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
  updated_by VARCHAR(64) NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bpm_audit_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  actor VARCHAR(64) NOT NULL,
  action_code VARCHAR(80) NOT NULL,
  resource_type VARCHAR(80) NOT NULL,
  operation VARCHAR(255) NOT NULL,
  request_summary VARCHAR(1000),
  success BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bpm_idempotency_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  request_key VARCHAR(128) NOT NULL UNIQUE,
  operation_name VARCHAR(255) NOT NULL,
  response_json TEXT,
  status VARCHAR(20) NOT NULL DEFAULT 'SUCCESS',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS bpm_event_log (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_key VARCHAR(255) NOT NULL UNIQUE,
  event_type VARCHAR(80) NOT NULL,
  process_instance_id VARCHAR(150),
  task_id VARCHAR(150),
  activity_id VARCHAR(150),
  payload_json TEXT,
  processed BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
