<template>
  <div class="app-shell" :class="{ 'app-shell-designer': view === 'designer' }">
    <aside class="sidebar">
      <div class="brand"><span class="brand-mark">P</span><div><b>POLARIS</b><small>流程审批中心</small></div></div>
      <div class="tenant"><i></i> 华东一厂 · BPM</div>
      <nav>
        <button v-for="item in nav" :key="item.key" :class="{active: view === item.key}" @click="switchView(item.key)"><span>{{ item.icon }}</span>{{ item.label }}<em v-if="item.badge">{{ item.badge }}</em></button>
      </nav>
      <div class="side-foot"><span class="online"></span> Flowable Engine Online <small>v0.1</small></div>
    </aside>
    <main class="main">
      <header><div><span class="crumb">POLARIS BPM /</span><strong>{{ currentLabel }}</strong></div><label class="actor-switch">当前用户 <input v-model="actor" @change="changeActor" /></label></header>
      <section class="content" :class="{ 'content-designer': view === 'designer' }">
        <div v-if="view !== 'designer'" class="heading"><div><p>POLARIS WORKFLOW</p><h1>{{ currentLabel }}</h1><span>{{ view === 'definitions' ? '从流程清单进入设计器，定义审批、业务动作、系统集成和跨业务流转' : '流程定义、审批任务、业务实例和工单联动统一管理' }}</span></div><div class="heading-actions"><button class="ghost" @click="loadAll">↻ 刷新</button><button v-if="view === 'definitions'" class="primary" @click="openNewDefinition">+ 新建流程</button><button v-if="view === 'forms'" class="primary" @click="openNewForm">+ 新建表单</button></div></div>

        <div v-if="view === 'dashboard'" class="dashboard">
          <div class="kpis"><article><span>流程定义</span><b>{{ overview.definitionCount || 0 }}</b><small>当前已发布版本</small></article><article><span>运行中实例</span><b>{{ overview.runningCount || 0 }}</b><small>业务审批进行中</small></article><article><span>今日审批动作</span><b>{{ overview.todayActionCount || 0 }}</b><small>通过 / 驳回 / 签收</small></article><article><span>我的待办</span><b>{{ overview.pendingCount || 0 }}</b><small>按当前用户权限</small></article></div>
          <div class="dashboard-grid">
            <div class="dashboard-primary">
              <article class="card task-card"><div class="card-head"><div><h2>待办任务</h2><small>优先处理影响生产节奏的申请</small></div><button class="link" @click="switchView('todo')">查看全部 →</button></div><div v-if="tasks.length" class="task-list"><div v-for="task in tasks.slice(0, 4)" :key="task.taskId" class="task-row"><span class="task-icon">{{ task.businessType === 'WORK_ORDER' ? '工' : '审' }}</span><div><b>{{ task.title }}</b><small>{{ task.name }} · {{ task.candidateGroup || '指定处理人' }}</small></div><button class="link" @click="openTask(task)">处理</button></div></div><div v-else class="empty compact-empty"><span class="empty-mark">✓</span><div><b>当前没有待办任务</b><small>新的审批任务会在这里出现</small></div><button class="link" @click="switchView('todo')">查看待办 →</button></div></article>
              <article class="card shortcuts"><div class="card-head"><div><h2>常用管理</h2><small>审批平台日常维护入口</small></div></div><div class="shortcut-grid"><button @click="switchView('definitions')"><b>◇</b><span>流程定义<small>发布与停用版本</small></span></button><button @click="switchView('forms')"><b>▤</b><span>表单配置<small>审批字段管理</small></span></button><button @click="switchView('instances')"><b>⌁</b><span>实例监控<small>查看审批轨迹</small></span></button><button @click="switchView('done')"><b>✓</b><span>我的已办<small>历史审批动作</small></span></button></div></article>
            </div>
            <article class="card integration"><div class="card-head"><div><h2>工单审批集成</h2><small>审批状态自动回写工单系统</small></div><span class="connected"><i></i>已连接</span></div><div class="flow"><div><b>工单</b><small>PLANNED</small></div><em>→</em><div class="blue"><b>Flowable</b><small>RUNNING</small></div><em>→</em><div class="green"><b>状态回写</b><small>PLANNED</small></div></div><p class="note">提交审批后，BPM 使用共享数据库中的 <code>work_order</code> 业务主键关联工单；审批通过回写为待排产，驳回回写为已驳回。</p><button class="primary full" @click="showStart = true">发起工单审批</button></article>
          </div>
        </div>

        <BpmDesigner v-if="view === 'designer'" :definition="designerDefinition" @close="switchView('definitions')" />

        <article v-if="view !== 'dashboard' && view !== 'designer'" class="card table-card">
          <div class="tabs"><button v-for="item in tabItems" :key="item.key" :class="{selected: view === item.key}" @click="switchView(item.key)">{{ item.label }}<i v-if="item.badge">{{ item.badge }}</i></button></div>
          <div class="filters"><input v-model="keyword" placeholder="搜索业务标题 / 流程名称" /><select v-if="view === 'todo' || view === 'done'" v-model="taskType"><option value="ALL">全部业务</option><option value="WORK_ORDER">工单审批</option><option value="BUSINESS">业务流转</option><option value="COMMON">通用审批</option></select><select v-if="view === 'instances'" v-model="instanceStatus"><option value="ALL">全部状态</option><option value="RUNNING">运行中</option><option value="APPROVED">已通过</option><option value="REJECTED">已驳回</option><option value="CANCELLED">已撤回</option></select><button class="ghost" @click="loadAll">筛选</button><span class="count">共 {{ rows.length }} 条</span></div>
          <table v-if="view === 'todo' || view === 'done'"><thead><tr><th>业务标题</th><th>当前节点</th><th>流程编码</th><th>候选角色</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.taskId"><td><b>{{ row.title }}</b><small>{{ row.businessType === 'WORK_ORDER' ? '工单 #' + row.businessId : row.businessType === 'BUSINESS' ? '业务 #' + (row.businessId || '-') : '通用申请' }}</small></td><td>{{ row.name }}</td><td>{{ row.processCode }}</td><td>{{ row.candidateGroup || row.assignee || '-' }}</td><td><span :class="['status', row.status.toLowerCase()]">{{ row.status === 'DONE' ? '已办' : '待处理' }}</span></td><td><button v-if="view === 'todo' && !row.assignee" class="link" @click="claim(row)">签收</button><button v-if="view === 'todo'" class="link" @click="openTask(row)">处理</button><button v-else class="link" @click="openInstance(row.instanceId)">查看实例</button></td></tr></tbody></table>
          <table v-else-if="view === 'instances'"><thead><tr><th>业务标题</th><th>流程编码</th><th>业务类型</th><th>发起人</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.flowable_instance_id"><td><b>{{ row.title }}</b><small>{{ row.flowable_instance_id }}</small></td><td>{{ row.process_code }}</td><td>{{ row.business_type === 'WORK_ORDER' ? '工单' : row.business_type === 'BUSINESS' ? '业务流转' : '通用' }}</td><td>{{ row.starter }}</td><td><span :class="['status', row.status.toLowerCase()]">{{ statusText(row.status) }}</span></td><td><button class="link" @click="openInstance(row.flowable_instance_id)">详情</button><button v-if="row.status === 'RUNNING'" class="link danger" @click="cancelInstance(row)">撤回</button></td></tr></tbody></table>
          <table v-else-if="view === 'definitions'"><thead><tr><th>流程编码</th><th>流程名称</th><th>类型 / 分类</th><th>版本</th><th>状态</th><th>最近更新</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td><b>{{ row.process_code }}</b><small>{{ row.trigger_type === 'EVENT' ? '事件触发' : row.trigger_type === 'SCHEDULE' ? '定时触发' : '人工触发' }}</small></td><td><b>{{ row.process_name }}</b><small>{{ row.description || '暂无流程说明' }}</small></td><td><span class="type-chip">{{ row.process_type === 'BUSINESS' ? '业务流程' : '审批流程' }}</span><small>{{ row.category || '未分类' }}</small></td><td>V{{ row.version }}</td><td><span :class="['status', String(row.status || '').toLowerCase()]">{{ row.status === 'PUBLISHED' ? '已发布' : row.status === 'SUSPENDED' ? '已停用' : '草稿' }}</span></td><td>{{ formatDate(row.updated_at || row.updatedAt) }}</td><td><button class="link" @click="openDesigner(row)">{{ row.status === 'DRAFT' ? '继续编辑' : '编辑' }}</button><button v-if="row.status !== 'DRAFT'" class="link" @click="startDefinition(row)">发起</button><button v-if="row.status !== 'DRAFT'" class="link" @click="toggleDefinition(row)">{{ row.status === 'SUSPENDED' ? '启用' : '停用' }}</button></td></tr></tbody></table>
          <table v-else><thead><tr><th>表单编码</th><th>表单名称</th><th>业务类型</th><th>状态</th><th>更新人</th><th>操作</th></tr></thead><tbody><tr v-for="row in rows" :key="row.form_code"><td>{{ row.form_code }}</td><td><b>{{ row.form_name }}</b></td><td>{{ row.business_type === 'WORK_ORDER' ? '工单' : row.business_type }}</td><td><span :class="['status', row.status.toLowerCase()]">{{ row.status === 'PUBLISHED' ? '已发布' : '草稿' }}</span></td><td>{{ row.updated_by }}</td><td><button class="link" @click="editForm(row)">编辑</button></td></tr></tbody></table>
          <div v-if="!rows.length" class="empty">暂无数据</div>
        </article>
      </section>
    </main>

    <div v-if="showTask" class="modal-mask"><div class="modal"><div class="modal-head"><div><h2>处理审批任务</h2><small>{{ activeTask.name }} · {{ activeTask.title }}</small></div><button @click="showTask = false">×</button></div><div class="summary"><b>{{ activeTask.title }}</b><small>流程：{{ activeTask.processCode }} · 候选角色：{{ activeTask.candidateGroup || '指定处理人' }}</small></div><label>审批意见<textarea v-model="comment" rows="4" placeholder="请输入审批意见（可选）"></textarea></label><div class="modal-actions"><button class="ghost" @click="showTask = false">取消</button><button class="reject" @click="completeTask(false)">驳回</button><button class="primary" @click="completeTask(true)">同意并提交</button></div></div></div>
    <div v-if="showStart" class="modal-mask"><div class="modal"><div class="modal-head"><h2>发起流程</h2><button @click="showStart = false">×</button></div><label>业务类型<select v-model="startForm.businessType"><option value="COMMON">通用业务</option><option value="BUSINESS">业务流转</option><option value="WORK_ORDER">工单</option></select></label><label>{{ startForm.businessType === 'WORK_ORDER' ? '工单 ID' : '业务 ID（可选）' }}<input v-model="startForm.businessId" :placeholder="startForm.businessType === 'WORK_ORDER' ? '例如 3' : '例如 order-2026-001'" /></label><label>实例标题<input v-model="startForm.title" placeholder="可选，默认自动生成" /></label><div class="modal-actions"><button class="ghost" @click="showStart = false">取消</button><button class="primary" @click="startWorkOrder">发起流程</button></div></div></div>
    <div v-if="showForm" class="modal-mask"><div class="modal"><div class="modal-head"><h2>{{ editingFormCode ? '编辑表单' : '新建表单' }}</h2><button @click="showForm = false">×</button></div><label>表单编码<input v-model="formForm.formCode" :disabled="Boolean(editingFormCode)" placeholder="FORM-PURCHASE-001" /></label><label>表单名称<input v-model="formForm.formName" placeholder="采购申请表" /></label><label>业务类型<select v-model="formForm.businessType"><option value="COMMON">通用</option><option value="WORK_ORDER">工单</option><option value="PURCHASE">采购</option></select></label><label>字段 JSON<textarea v-model="formForm.schemaJson" rows="5"></textarea></label><div class="modal-actions"><button class="ghost" @click="showForm = false">取消</button><button class="primary" @click="saveForm">保存</button></div></div></div>
    <div v-if="showInstance" class="modal-mask"><div class="modal wide"><div class="modal-head"><h2>流程实例详情</h2><button @click="showInstance = false">×</button></div><div v-if="instanceDetail.instance"><div class="summary"><b>{{ instanceDetail.instance.title }}</b><small>{{ statusText(instanceDetail.instance.status) }} · 发起人 {{ instanceDetail.instance.starter }}</small></div><h3>审批轨迹</h3><div v-for="item in instanceDetail.history || []" :key="item.taskId" class="history"><b>{{ item.name }}</b><small>{{ item.assignee || '待签收' }} · {{ formatDate(item.startTime) }}<template v-if="item.endTime"> → {{ formatDate(item.endTime) }}</template></small></div></div></div></div>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { request } from './api'
import BpmDesigner from './components/BpmDesigner.vue'

const nav = [{ key: 'dashboard', label: '审批工作台', icon: '▦' }, { key: 'todo', label: '我的待办', icon: '⇩', badge: 3 }, { key: 'done', label: '我的已办', icon: '✓' }, { key: 'instances', label: '流程实例', icon: '⌁' }, { key: 'definitions', label: '流程定义', icon: '◇' }, { key: 'forms', label: '表单配置', icon: '▤' }]
const tabItems = nav.filter(item => item.key !== 'dashboard')
const view = ref('dashboard'); const actor = ref(localStorage.getItem('bpm-user') || 'admin'); const keyword = ref(''); const taskType = ref('ALL'); const instanceStatus = ref('ALL')
const overview = ref({}); const tasks = ref([]); const done = ref([]); const instances = ref([]); const definitions = ref([]); const forms = ref([]); const activeTask = ref({}); const instanceDetail = ref({}); const designerDefinition = ref(null)
const showTask = ref(false); const showStart = ref(false); const showForm = ref(false); const showInstance = ref(false); const comment = ref(''); const editingFormCode = ref('')
const startForm = ref({ processCode: 'workOrderApproval', businessType: 'WORK_ORDER', businessId: '', title: '' }); const formForm = ref({ formCode: '', formName: '', businessType: 'COMMON', schemaJson: '{"fields":[]}' })
const currentLabel = computed(() => nav.find(item => item.key === view.value)?.label || '审批工作台')
const rows = computed(() => { let result = view.value === 'todo' ? tasks.value : view.value === 'done' ? done.value : view.value === 'instances' ? instances.value : view.value === 'definitions' ? definitions.value : forms.value; if (keyword.value) result = result.filter(row => JSON.stringify(row).toLowerCase().includes(keyword.value.toLowerCase())); if (view.value === 'todo' || view.value === 'done') result = result.filter(row => taskType.value === 'ALL' || row.businessType === taskType.value); if (view.value === 'instances' && instanceStatus.value !== 'ALL') result = result.filter(row => row.status === instanceStatus.value); return result })
function switchView(next) { view.value = next; keyword.value = ''; loadAll() }
function openNewDefinition() { const suffix = new Date().toISOString().replace(/\D/g, '').slice(0, 14); designerDefinition.value = { isNew: true, process_code: `businessFlow_${suffix}`, process_name: '新业务流程', process_type: 'BUSINESS', trigger_type: 'MANUAL', category: '通用业务', version: 1, status: 'DRAFT' }; view.value = 'designer' }
function openDesigner(row = null) { designerDefinition.value = row || definitions.value[0] || { isNew: true, process_code: 'businessFlow', process_name: '新业务流程', process_type: 'BUSINESS', trigger_type: 'MANUAL', version: 1, status: 'DRAFT' }; view.value = 'designer' }
function changeActor() { localStorage.setItem('bpm-user', actor.value); loadAll() }
async function loadAll() { try { overview.value = await request('/bpm/overview') || {}; definitions.value = await request('/bpm/process-definitions') || []; forms.value = await request('/bpm/forms') || []; tasks.value = await request('/bpm/tasks?scope=todo') || []; done.value = await request('/bpm/tasks?scope=done') || []; instances.value = await request('/bpm/instances') || [] } catch (error) { overview.value = {}; definitions.value = []; forms.value = []; tasks.value = []; done.value = []; instances.value = []; console.error(error) } }
function openTask(task) { activeTask.value = task; comment.value = ''; showTask.value = true }
async function completeTask(approved) { await request(`/bpm/tasks/${activeTask.value.taskId}/complete`, { method: 'POST', body: JSON.stringify({ approved, comment: comment.value }), allowFallback: false }); showTask.value = false; await loadAll() }
async function claim(row) { await request(`/bpm/tasks/${row.taskId}/claim`, { method: 'POST', body: '{}', allowFallback: false }); await loadAll() }
function openInstance(id) { request(`/bpm/instances/${id}`).then(data => { instanceDetail.value = data || { instance: instances.value.find(row => row.flowable_instance_id === id), history: [] }; showInstance.value = true }) }
function startDefinition(row) { startForm.value = { processCode: row.process_code, businessType: row.process_type === 'BUSINESS' ? 'BUSINESS' : row.process_code === 'workOrderApproval' ? 'WORK_ORDER' : 'COMMON', businessId: '', title: '' }; showStart.value = true }
async function startWorkOrder() { await request('/bpm/process-instances', { method: 'POST', body: JSON.stringify({ ...startForm.value }), allowFallback: false }); showStart.value = false; await loadAll(); switchView('instances') }
async function cancelInstance(row) { if (!window.confirm(`确认撤回“${row.title}”吗？`)) return; await request(`/bpm/instances/${row.flowable_instance_id}/cancel`, { method: 'POST', body: '{}', allowFallback: false }); await loadAll() }
async function toggleDefinition(row) { await request(`/bpm/process-definitions/${row.id}/toggle`, { method: 'POST', body: JSON.stringify({ suspended: row.status !== 'SUSPENDED' }), allowFallback: false }); await loadAll() }
function openNewForm() { editingFormCode.value = ''; formForm.value = { formCode: '', formName: '', businessType: 'COMMON', schemaJson: '{"fields":[]}' }; showForm.value = true }
function editForm(row) { editingFormCode.value = row.form_code; formForm.value = { formCode: row.form_code, formName: row.form_name, businessType: row.business_type, schemaJson: row.schema_json || '{"fields":[]}' }; showForm.value = true }
async function saveForm() { const path = editingFormCode.value ? `/bpm/forms/${editingFormCode.value}` : '/bpm/forms'; await request(path, { method: editingFormCode.value ? 'PUT' : 'POST', body: JSON.stringify(formForm.value), allowFallback: false }); showForm.value = false; await loadAll() }
function statusText(value) { return ({ RUNNING: '运行中', APPROVED: '已通过', REJECTED: '已驳回', CANCELLED: '已撤回' }[value] || value || '-') }
function formatDate(value) { return value ? String(value).replace('T', ' ').slice(0, 16) : '-' }
onMounted(loadAll)
</script>
