<template>
  <section class="designer-shell">
    <div class="designer-header">
      <div class="designer-title-group">
        <button class="designer-back" title="返回流程定义" @click="emit('close')">‹</button>
        <div>
          <div class="designer-breadcrumb">流程中心 / 流程定义 / 设计器</div>
          <div class="designer-title-line">
            <input v-model="process.name" class="designer-name-input" @input="fieldChanged('修改流程名称')" />
            <span class="version-badge">草稿 V{{ process.version }}</span>
            <span :class="['designer-save-state', saveStateClass]"><i></i>{{ saveState }}</span>
          </div>
        </div>
      </div>
      <div class="designer-header-actions">
        <button class="toolbar-button" @click="undo" :disabled="!undoStack.length" title="撤销">↶ <span>撤销</span></button>
        <button class="toolbar-button" @click="redo" :disabled="!redoStack.length" title="重做">↷ <span>重做</span></button>
        <span class="toolbar-divider"></span>
        <button class="toolbar-button" @click="runValidation">✓ 校验 <em v-if="validation.length">{{ validation.length }}</em></button>
        <button class="toolbar-button" @click="showPreview = true">▷ 预览</button>
        <button class="button-ghost" @click="saveDesign(false)">保存草稿</button>
        <button class="button-primary" @click="publishDesign">发布流程</button>
      </div>
    </div>

    <div class="designer-meta-bar">
      <div class="meta-item"><span>流程编码</span><b>{{ process.code }}</b></div>
      <div class="meta-item"><span>归属分类</span><b>{{ process.category || '未分类' }}</b></div>
      <div class="meta-item"><span>流程负责人</span><b>{{ process.owner || 'admin' }}</b></div>
      <div class="meta-item"><span>节点</span><b>{{ nodes.length }}</b></div>
      <div class="meta-item"><span>连线</span><b>{{ edges.length }}</b></div>
      <div class="meta-spacer"></div>
      <span v-if="connectingFrom" class="connect-tip">请选择目标节点完成连线 · Esc 取消</span>
      <button class="meta-link" @click="bottomPanel = bottomPanel === 'json' ? '' : 'json'">查看 JSON</button>
      <button class="meta-link" @click="openProcessSettings">流程设置</button>
    </div>

    <div class="designer-workspace" :class="{ 'palette-collapsed': paletteCollapsed }">
      <aside class="designer-palette">
        <div class="panel-title-row">
          <div><h3>节点工具箱</h3><small>拖拽节点到画布</small></div>
          <button class="panel-collapse" :title="paletteCollapsed ? '展开工具箱' : '收起工具箱'" @click="paletteCollapsed = !paletteCollapsed">{{ paletteCollapsed ? '›' : '‹' }}</button>
        </div>
        <div class="palette-search"><span>⌕</span><input v-model="paletteKeyword" placeholder="搜索节点" /></div>
        <div v-for="group in filteredPalette" :key="group.name" class="palette-group">
          <div class="palette-group-title"><span>{{ group.name }}</span><i>{{ group.items.length }}</i></div>
          <button v-for="item in group.items" :key="item.type" class="palette-node" draggable="true" @dragstart="dragPalette($event, item)" @click="addFromPalette(item.type)">
            <span :class="['palette-icon', `tone-${item.tone}`]">{{ item.icon }}</span>
            <span class="palette-copy"><b>{{ item.label }}</b><small>{{ item.description }}</small></span>
            <span class="palette-add">+</span>
          </button>
        </div>
        <div class="palette-foot"><span class="keyboard-key">D</span> 快速复制节点 <span class="keyboard-key">⌫</span> 删除节点</div>
      </aside>

      <section class="designer-canvas-panel">
        <div class="canvas-toolbar">
          <div class="canvas-mode"><button :class="{active: canvasMode === 'select'}" @click="canvasMode = 'select'">↖ 选择</button><button :class="{active: canvasMode === 'connect'}" @click="canvasMode = 'connect'">⌁ 连线</button><button :class="{active: canvasMode === 'pan'}" @click="canvasMode = 'pan'">✥ 画布</button></div>
          <div class="canvas-toolbar-actions"><span class="canvas-help">拖拽空白区域平移 · 滚轮缩放</span><button @click="fitCanvas">适应画布</button><button class="toolbar-icon-button" @click="centerCanvas" title="将流程定位到画布中心">◎</button><button @click="zoomOut">−</button><span class="zoom-value">{{ Math.round(zoom * 100) }}%</span><button @click="zoomIn">＋</button></div>
        </div>
        <div ref="canvasViewport" :class="['canvas-viewport', `mode-${canvasMode}`, { 'is-panning': isPanning } ]" @pointerdown="handleViewportPointerDown" @dragover.prevent @drop="dropNode" @wheel.prevent="zoomByWheel" @contextmenu.prevent>
          <div class="canvas-ruler horizontal"><span v-for="mark in rulerMarks" :key="`h-${mark}`" :style="{left: `${mark}px`}">{{ mark }}</span></div>
          <div class="canvas-ruler vertical"><span v-for="mark in rulerMarks" :key="`v-${mark}`" :style="{top: `${mark}px`}">{{ mark }}</span></div>
          <div class="canvas-stage" :style="stageStyle">
            <svg class="connection-layer" :width="stageWidth" :height="stageHeight" aria-label="流程连线">
              <defs>
                <pattern id="smallGrid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M 20 0 L 0 0 0 20" fill="none" stroke="#e8eef5" stroke-width="1" /></pattern>
                <pattern id="largeGrid" width="100" height="100" patternUnits="userSpaceOnUse"><rect width="100" height="100" fill="url(#smallGrid)" /><path d="M 100 0 L 0 0 0 100" fill="none" stroke="#dbe5ef" stroke-width="1" /></pattern>
                <marker id="arrowHead" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#7e9bb8" /></marker>
                <marker id="arrowHeadSelected" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 z" fill="#236bd3" /></marker>
              </defs>
              <rect width="100%" height="100%" fill="url(#largeGrid)" />
              <g v-for="edge in edges" :key="edge.id">
                <path :d="edgePath(edge)" class="connection-hit" @click.stop="selectEdge(edge)" />
                <path :d="edgePath(edge)" :class="['connection-line', {selected: selectedEdgeId === edge.id}]" :marker-end="selectedEdgeId === edge.id ? 'url(#arrowHeadSelected)' : 'url(#arrowHead)'" @click.stop="selectEdge(edge)" />
                <text v-if="edge.condition" :x="edgeLabelPoint(edge).x" :y="edgeLabelPoint(edge).y" class="connection-label" @click.stop="selectEdge(edge)">{{ edge.condition }}</text>
              </g>
              <path v-if="connectingFrom" :d="connectionPreviewPath" class="connection-preview" />
            </svg>
          <div v-for="node in nodes" :key="node.id" :class="nodeClasses(node)" :style="nodeStyle(node)" role="button" tabindex="0" :aria-label="`${node.label}，${nodeMeta(node.type).label}`" @pointerdown.stop="startNodeDrag($event, node)" @click.stop="selectNode(node)" @keydown.enter.stop="selectNode(node)">
              <span class="node-status-dot"></span>
              <span class="node-symbol">{{ nodeMeta(node.type).icon }}</span>
              <span class="node-content"><b>{{ node.label || nodeMeta(node.type).label }}</b><small>{{ nodeSubtitle(node) }}</small></span>
              <button v-for="port in ports" :key="`port-${node.id}-${port}`" :class="['node-port', `port-${port}`, portClass(node)]" :title="portTitle(node, port)" @pointerdown.stop="handlePortPointerDown($event, node, port)" @pointerup.stop="handlePortPointerUp($event, node, port)" @click.stop="handlePortClick(node, port)"></button>
              <span v-if="selectedNodeId === node.id" class="node-quick-actions"><button @click.stop="duplicateNode(node)">⧉</button><button @click.stop="removeNode(node)">×</button></span>
            </div>
          </div>
          <div class="canvas-empty-hint" v-if="!nodes.length"><b>从左侧拖入第一个节点</b><small>建议先放置开始事件，再逐步配置审批与业务节点</small></div>
          <div class="minimap"><div class="minimap-title"><span>画布导航</span><span>{{ Math.round(zoom * 100) }}%</span></div><div class="minimap-stage" @pointerdown.stop="jumpToMiniMap"><span v-for="node in nodes" :key="`mini-${node.id}`" :class="['mini-node', `mini-${node.type}`]" :style="miniNodeStyle(node)"></span><div class="mini-viewport" :style="miniViewportStyle"></div></div></div>
        </div>
        <div class="designer-bottom-bar">
          <div class="bottom-tabs"><button :class="{active: bottomPanel === 'validation'}" @click="toggleBottomPanel('validation')">流程校验 <i :class="{danger: hasValidationErrors}">{{ validation.length }}</i></button><button :class="{active: bottomPanel === 'changes'}" @click="toggleBottomPanel('changes')">变更记录 <i>{{ history.length }}</i></button><button :class="{active: bottomPanel === 'json'}" @click="toggleBottomPanel('json')">定义 JSON</button></div>
          <div class="bottom-shortcuts"><span><kbd>⌘</kbd><kbd>S</kbd> 保存</span><span><kbd>⌘</kbd><kbd>Z</kbd> 撤销</span><span><kbd>Esc</kbd> 取消连线</span></div>
        </div>
        <div v-if="bottomPanel" class="bottom-panel-content">
          <div v-if="bottomPanel === 'validation'" class="validation-panel"><div class="validation-summary"><span :class="['validation-icon', {ok: !hasValidationErrors}]">{{ hasValidationErrors ? '!' : '✓' }}</span><div><b>{{ hasValidationErrors ? '发现需要处理的问题' : '流程结构校验通过' }}</b><small>{{ hasValidationErrors ? '发布前请处理阻断项；警告项可按业务规则决定是否修正。' : '当前流程具备完整的开始、审批和结束路径，可以进入发布审核。' }}</small></div><button class="button-ghost" @click="runValidation">重新校验</button></div><div v-if="validation.length" class="validation-list"><div v-for="item in validation" :key="item.id" :class="['validation-row', item.level]"><span>{{ item.level === 'error' ? '×' : '!' }}</span><div><b>{{ item.title }}</b><small>{{ item.message }}</small></div><button @click="focusIssue(item)">定位</button></div></div><div v-else class="validation-clear">没有发现结构问题。可继续完善节点表单、权限与超时策略。</div></div>
          <div v-else-if="bottomPanel === 'changes'" class="change-panel"><div class="change-head"><b>本次编辑会话</b><span>共 {{ history.length }} 项变更</span></div><div v-if="history.length" class="change-list"><div v-for="item in history.slice(0, 12)" :key="item.id" class="change-row"><span class="change-dot"></span><div><b>{{ item.label }}</b><small>{{ item.time }}</small></div></div></div><div v-else class="validation-clear">还没有编辑记录，拖入或修改节点后会显示在这里。</div></div>
          <div v-else class="json-panel"><div class="json-head"><b>当前流程定义快照</b><button class="meta-link" @click="copyJson">复制 JSON</button></div><pre>{{ definitionJson }}</pre></div>
        </div>
      </section>

      <aside class="designer-inspector">
        <div class="inspector-tabs"><button :class="{active: inspectorTab === 'properties'}" @click="inspectorTab = 'properties'">属性</button><button :class="{active: inspectorTab === 'variables'}" @click="inspectorTab = 'variables'">变量 <i>{{ variables.length }}</i></button><button :class="{active: inspectorTab === 'audit'}" @click="inspectorTab = 'audit'">审计</button></div>
        <div v-if="inspectorTab === 'properties'" class="inspector-scroll">
          <div v-if="selectedNode" class="inspector-heading"><span :class="['inspector-symbol', `tone-${nodeMeta(selectedNode.type).tone}`]">{{ nodeMeta(selectedNode.type).icon }}</span><div><b>{{ nodeMeta(selectedNode.type).label }}</b><small>{{ selectedNode.id }}</small></div><button class="inspector-delete" @click="removeNode(selectedNode)">⌫</button></div>
          <div v-else-if="selectedEdge" class="inspector-heading"><span class="inspector-symbol tone-blue">⌁</span><div><b>条件连线</b><small>{{ selectedEdge.source }} → {{ selectedEdge.target }}</small></div><button class="inspector-delete" @click="removeEdge(selectedEdge)">⌫</button></div>
          <div v-else class="inspector-heading"><span class="inspector-symbol tone-indigo">⌘</span><div><b>流程属性</b><small>未选择节点</small></div></div>

          <template v-if="selectedNode">
            <div class="property-section"><div class="section-label">基础信息 <span>Basic</span></div><label class="field-label">节点名称<input v-model="selectedNode.label" @input="fieldChanged('修改节点名称')" /></label><label class="field-label">节点编码<input v-model="selectedNode.code" @input="fieldChanged('修改节点编码')" /></label><label class="field-label">节点说明<textarea v-model="selectedNode.description" rows="2" placeholder="描述该节点的业务目的" @input="fieldChanged('修改节点说明')"></textarea></label></div>
            <div v-if="selectedNode.type === 'userTask'" class="property-section"><div class="section-label">审批人配置 <span>Assignee</span></div><label class="field-label">分配方式<select v-model="selectedNode.assigneeMode" @change="fieldChanged('修改分配方式')"><option value="group">候选角色</option><option value="user">指定用户</option><option value="expression">表达式</option></select></label><label v-if="selectedNode.assigneeMode === 'group'" class="field-label">候选角色<input v-model="selectedNode.candidateGroups" placeholder="planner, admin" @input="fieldChanged('修改候选角色')" /><small class="field-hint">多个角色使用逗号分隔，任一角色均可签收。</small></label><label v-else-if="selectedNode.assigneeMode === 'user'" class="field-label">指定用户<input v-model="selectedNode.assignee" placeholder="输入用户编码" @input="fieldChanged('修改指定用户')" /></label><label v-else class="field-label">用户表达式<input v-model="selectedNode.assigneeExpression" placeholder="${initiator}" @input="fieldChanged('修改用户表达式')" /></label><label class="field-label">绑定表单<select v-model="selectedNode.formCode" @change="fieldChanged('绑定节点表单')"><option value="">不绑定表单</option><option value="FORM-WORK-ORDER-APPROVAL">工单发布审批表</option><option value="FORM-PURCHASE-001">采购申请表</option><option value="FORM-QUALITY-001">质量异常处置表</option></select></label><div class="inline-fields"><label class="field-label">处理时限<input v-model.number="selectedNode.dueDays" type="number" min="0" @input="fieldChanged('修改处理时限')" /></label><label class="field-label">超时策略<select v-model="selectedNode.timeoutAction" @change="fieldChanged('修改超时策略')"><option value="remind">提醒</option><option value="escalate">升级</option><option value="autoReject">自动驳回</option></select></label></div><label class="switch-row"><input v-model="selectedNode.requireComment" type="checkbox" @change="fieldChanged('修改审批意见策略')" /><span class="switch-ui"></span><span>完成时必须填写审批意见</span></label><label class="switch-row"><input v-model="selectedNode.allowTransfer" type="checkbox" @change="fieldChanged('修改转办策略')" /><span class="switch-ui"></span><span>允许处理人转办</span></label></div>
            <div v-if="selectedNode.type === 'serviceTask'" class="property-section"><div class="section-label">业务动作 <span>Service</span></div><label class="field-label">服务键<input v-model="selectedNode.serviceKey" placeholder="business.setStatus / workOrder.updateStatus" @input="fieldChanged('修改服务键')" /><small class="field-hint">服务键是后端业务动作注册表的稳定标识，执行结果会写入流程变量。</small></label><label class="field-label">执行方式<select v-model="selectedNode.serviceType" @change="fieldChanged('修改执行方式')"><option value="delegate">后端业务动作</option><option value="expression">表达式</option><option value="webhook">Webhook</option></select></label><label class="field-label">失败重试<select v-model="selectedNode.retry" @change="fieldChanged('修改重试策略')"><option value="0">不重试</option><option value="3">失败后重试 3 次</option><option value="5">失败后重试 5 次</option></select></label></div>
            <div v-if="selectedNode.type === 'subprocess'" class="property-section"><div class="section-label">子流程调用 <span>Call activity</span></div><label class="field-label">被调用流程编码<input v-model="selectedNode.processRef" placeholder="inventory.receive" @input="fieldChanged('修改子流程编码')" /><small class="field-hint">被调用流程需要先发布；运行时会按流程编码进入独立的子流程实例。</small></label></div>
            <div v-if="selectedNode.type === 'exclusiveGateway' || selectedNode.type === 'inclusiveGateway'" class="property-section"><div class="section-label">网关策略 <span>Gateway</span></div><label class="field-label">默认路径<select v-model="selectedNode.defaultEdge" @change="fieldChanged('修改默认路径')"><option value="">未设置</option><option v-for="edge in outgoingEdges(selectedNode.id)" :key="edge.id" :value="edge.id">{{ edge.condition || edge.id }}</option></select></label><label class="switch-row"><input v-model="selectedNode.waitForAll" type="checkbox" @change="fieldChanged('修改网关等待策略')" /><span class="switch-ui"></span><span>等待所有分支完成</span></label><p class="property-callout">在连线上设置条件表达式，网关会按照变量值选择下一条路径。</p></div>
            <div v-if="selectedNode.type === 'timerEvent'" class="property-section"><div class="section-label">定时策略 <span>Timer</span></div><label class="field-label">定时类型<select v-model="selectedNode.timerType" @change="fieldChanged('修改定时类型')"><option value="duration">持续时间</option><option value="date">指定时间</option><option value="cycle">循环周期</option></select></label><label class="field-label">定时表达式<input v-model="selectedNode.timerValue" placeholder="PT2H / R3/PT1D" @input="fieldChanged('修改定时表达式')" /></label></div>
            <div v-if="selectedNode.type === 'messageEvent'" class="property-section"><div class="section-label">消息触发 <span>Message</span></div><label class="field-label">消息名称<input v-model="selectedNode.messageName" placeholder="workOrder.approved" @input="fieldChanged('修改消息名称')" /></label><label class="field-label">消息变量<input v-model="selectedNode.messageVariable" placeholder="businessId" @input="fieldChanged('修改消息变量')" /></label></div>
          </template>

          <template v-else-if="selectedEdge">
            <div class="property-section"><div class="section-label">连线条件 <span>Condition</span></div><label class="field-label">条件名称<input v-model="selectedEdge.condition" placeholder="审批通过" @input="fieldChanged('修改条件名称')" /></label><label class="field-label">表达式<textarea v-model="selectedEdge.expression" rows="3" placeholder="${approved == true}" @input="fieldChanged('修改条件表达式')"></textarea></label><label class="switch-row"><input v-model="selectedEdge.isDefault" type="checkbox" @change="fieldChanged('设置默认路径')" /><span class="switch-ui"></span><span>设为默认路径</span></label></div>
          </template>

          <template v-else>
            <div class="property-section"><div class="section-label">流程标识 <span>Identity</span></div><label class="field-label">流程编码<input v-model="process.code" :disabled="!isNewDefinition && Boolean(definitionCode)" placeholder="例如 purchase_to_stock" @input="fieldChanged('修改流程编码')" /><small class="field-hint">只能使用英文、数字和下划线；发布后作为业务接口的稳定标识。</small></label><label class="field-label">流程名称<input v-model="process.name" @input="fieldChanged('修改流程名称')" /></label><div class="inline-fields"><label class="field-label">流程类型<select v-model="process.processType" @change="fieldChanged('修改流程类型')"><option value="BUSINESS">业务流程</option><option value="APPROVAL">审批流程</option></select></label><label class="field-label">触发方式<select v-model="process.triggerType" @change="fieldChanged('修改触发方式')"><option value="MANUAL">人工发起</option><option value="EVENT">业务事件</option><option value="SCHEDULE">定时触发</option></select></label></div><label class="field-label">业务分类<select v-model="process.category" @change="fieldChanged('修改业务分类')"><option>生产制造</option><option>仓储物流</option><option>质量管理</option><option>采购协同</option><option>通用审批</option><option>跨业务协同</option></select></label><label class="field-label">流程描述<textarea v-model="process.description" rows="3" @input="fieldChanged('修改流程描述')"></textarea></label></div><div class="property-section"><div class="section-label">运行设置 <span>Runtime</span></div><label class="field-label">实例标题模板<input v-model="process.titleTemplate" placeholder="${businessType} - ${businessId}" @input="fieldChanged('修改实例标题模板')" /></label><label class="switch-row"><input v-model="process.allowWithdraw" type="checkbox" @change="fieldChanged('修改撤回策略')" /><span class="switch-ui"></span><span>允许发起人撤回</span></label><label class="switch-row"><input v-model="process.enableHistory" type="checkbox" @change="fieldChanged('修改历史记录策略')" /><span class="switch-ui"></span><span>保留完整审批轨迹</span></label></div>
          </template>
        </div>
        <div v-else-if="inspectorTab === 'variables'" class="inspector-scroll"><div class="inspector-heading"><span class="inspector-symbol tone-green">⌘</span><div><b>流程变量</b><small>Variables</small></div><button class="icon-plus" @click="addVariable">+</button></div><p class="inspector-intro">变量贯穿流程实例生命周期，可用于网关条件、表单回填和服务节点参数。</p><div v-for="(variable, index) in variables" :key="variable.id" class="variable-card"><div class="variable-index">{{ String(index + 1).padStart(2, '0') }}</div><div class="variable-body"><input v-model="variable.key" placeholder="变量编码" @input="fieldChanged('修改变量编码')" /><input v-model="variable.label" placeholder="显示名称" @input="fieldChanged('修改变量名称')" /><div class="inline-fields"><select v-model="variable.type" @change="fieldChanged('修改变量类型')"><option>string</option><option>number</option><option>boolean</option><option>date</option><option>json</option></select><input v-model="variable.defaultValue" placeholder="默认值" @input="fieldChanged('修改变量默认值')" /></div></div><button class="variable-remove" @click="removeVariable(variable)">×</button></div><div v-if="!variables.length" class="empty-inspector"><span>⌘</span><b>暂无流程变量</b><small>点击右上角 + 添加第一个变量</small></div></div>
        <div v-else class="inspector-scroll audit-panel"><div class="inspector-heading"><span class="inspector-symbol tone-violet">◎</span><div><b>审计信息</b><small>Audit trail</small></div></div><div class="audit-card"><span>创建人</span><b>{{ process.createdBy || 'admin' }}</b></div><div class="audit-card"><span>最后修改</span><b>{{ process.updatedBy || 'admin' }}</b><small>{{ saveState === '已保存' ? '刚刚保存' : '当前编辑会话' }}</small></div><div class="audit-card"><span>版本状态</span><b class="audit-green">草稿</b><small>发布后将生成新版本</small></div><div class="audit-divider"></div><div class="audit-event" v-for="item in history.slice(0, 6)" :key="`audit-${item.id}`"><i></i><div><b>{{ item.label }}</b><small>{{ item.time }}</small></div></div></div>
      </aside>
    </div>

    <div v-if="showPreview" class="preview-mask" @click.self="showPreview = false"><div class="preview-dialog"><div class="preview-head"><div><span class="preview-kicker">PROCESS PREVIEW</span><h2>{{ process.name }}</h2><small>{{ process.code }} · V{{ process.version }} · 交互预览</small></div><button @click="showPreview = false">×</button></div><div class="preview-body"><div class="preview-flow"><div v-for="node in nodes" :key="`preview-${node.id}`" class="preview-node-wrap"><div :class="['preview-node', `preview-${node.type}`]"><span>{{ nodeMeta(node.type).icon }}</span><b>{{ node.label }}</b><small>{{ nodeSubtitle(node) }}</small></div><i v-if="node !== nodes[nodes.length - 1]">→</i></div></div><div class="preview-callout"><span>ⓘ</span><div><b>这是只读运行预览</b><small>实际运行时将根据表单数据、候选角色和网关表达式动态计算路径。</small></div></div></div><div class="preview-actions"><button class="button-ghost" @click="showPreview = false">关闭预览</button><button class="button-primary" @click="showPreview = false; bottomPanel = 'validation'">查看校验结果</button></div></div></div>
  </section>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, reactive, ref, watch } from 'vue'
import { request } from '../api'
import { bestPorts, connectionLabelPoint, connectionPath, connectionPreviewPath as buildConnectionPreviewPath, nodeSize, portPoint } from '../connectionGeometry'

const props = defineProps({ definition: { type: Object, default: null } })
const emit = defineEmits(['close'])

const palette = [
  { name: '事件节点', items: [{ type: 'start', label: '开始事件', description: '流程启动入口', icon: '▶', tone: 'green' }, { type: 'timerEvent', label: '定时事件', description: '按时间触发流程', icon: '◷', tone: 'orange' }, { type: 'messageEvent', label: '消息事件', description: '按业务消息触发', icon: '✉', tone: 'violet' }, { type: 'end', label: '结束事件', description: '流程完成出口', icon: '■', tone: 'red' }] },
  { name: '任务节点', items: [{ type: 'userTask', label: '人工审批', description: '指定角色或用户处理', icon: 'A', tone: 'blue' }, { type: 'serviceTask', label: '业务动作', description: '推进业务状态或调用系统服务', icon: '⚙', tone: 'indigo' }, { type: 'subprocess', label: '子流程', description: '复用已定义的流程', icon: '▣', tone: 'cyan' }] },
  { name: '网关节点', items: [{ type: 'exclusiveGateway', label: '条件网关', description: '选择一条条件分支', icon: '◇', tone: 'orange' }, { type: 'parallelGateway', label: '并行网关', description: '同时执行多个分支', icon: '+', tone: 'blue' }, { type: 'inclusiveGateway', label: '包容网关', description: '按条件执行多个分支', icon: '○', tone: 'violet' }] }
]

const defaultProcess = { code: 'workOrderApproval', name: '工单发布审批', description: '生产工单发布前的多级审批流程', category: '生产制造', processType: 'APPROVAL', triggerType: 'MANUAL', owner: 'admin', version: 1, titleTemplate: '${businessType} - ${businessId}', allowWithdraw: true, enableHistory: true, createdBy: 'system', updatedBy: 'admin' }
function baseNode(type, x, y, extra = {}) { return { id: `${type}_${Date.now()}_${Math.floor(Math.random() * 999)}`, type, code: type, label: nodeMeta(type).label, description: '', x, y, ...nodeDefaults(type), ...extra } }
function nodeDefaults(type) {
  return { assigneeMode: 'group', candidateGroups: 'planner', assignee: '', assigneeExpression: '', formCode: '', dueDays: 2, timeoutAction: 'remind', requireComment: true, allowTransfer: true, serviceKey: '', serviceType: 'delegate', retry: '3', processRef: '', calledProcess: '', timerType: 'duration', timerValue: 'PT2H', messageName: '', messageVariable: '', defaultEdge: '', waitForAll: false }
}
function createDefaultNodes() { return [baseNode('start', 120, 205, { id: 'start_1', code: 'start', label: '提交申请' }), baseNode('userTask', 360, 175, { id: 'approval_1', code: 'plannerReview', label: '计划员审核', description: '计划员审核工单的生产可行性', candidateGroups: 'planner', formCode: 'FORM-WORK-ORDER-APPROVAL' }), baseNode('exclusiveGateway', 665, 190, { id: 'gateway_1', code: 'approvalDecision', label: '审批结果', description: '根据审批结果选择下一步' }), baseNode('serviceTask', 865, 90, { id: 'service_1', code: 'updateStatus', label: '更新工单状态', description: '将工单状态更新为待排产', serviceKey: 'workOrder.updateStatus' }), baseNode('userTask', 865, 300, { id: 'warehouseReview_1', code: 'warehouseReview', label: '仓库确认', candidateGroups: 'warehouse', dueDays: 1 }), baseNode('end', 1150, 105, { id: 'end_approved', code: 'approved', label: '审批完成' }), baseNode('end', 1150, 315, { id: 'end_rejected', code: 'rejected', label: '驳回结束' })] }
function createDefaultEdges() { return [{ id: 'edge_start_approval', source: 'start_1', target: 'approval_1', condition: '', expression: '', isDefault: false }, { id: 'edge_approval_gateway', source: 'approval_1', target: 'gateway_1', condition: '', expression: '', isDefault: false }, { id: 'edge_gateway_service', source: 'gateway_1', target: 'service_1', condition: '通过', expression: '${approved == true}', isDefault: false }, { id: 'edge_gateway_review', source: 'gateway_1', target: 'warehouseReview_1', condition: '需复核', expression: '${requiresReview == true}', isDefault: false }, { id: 'edge_service_end', source: 'service_1', target: 'end_approved', condition: '', expression: '', isDefault: false }, { id: 'edge_review_end', source: 'warehouseReview_1', target: 'end_rejected', condition: '驳回', expression: '${approved == false}', isDefault: true }] }

const process = reactive({ ...defaultProcess })
const nodes = ref(createDefaultNodes())
const edges = ref(createDefaultEdges())
const variables = ref([{ id: 'var_1', key: 'approved', label: '审批结果', type: 'boolean', defaultValue: '' }, { id: 'var_2', key: 'requiresReview', label: '需要复核', type: 'boolean', defaultValue: 'false' }])
const selectedNodeId = ref('approval_1'); const selectedEdgeId = ref(''); const connectingFrom = ref(null); const connectionSourcePort = ref('right'); const connectionCursor = ref({ x: 0, y: 0 })
const paletteKeyword = ref(''); const paletteCollapsed = ref(false); const zoom = ref(0.9); const pan = reactive({ x: 0, y: 0 }); const canvasMode = ref('select'); const bottomPanel = ref(''); const inspectorTab = ref('properties'); const spacePressed = ref(false); const isPanning = ref(false)
const canvasViewport = ref(null); const showPreview = ref(false); const saveState = ref('未保存'); const dirty = ref(true); const saving = ref(false); const history = ref([]); const undoStack = ref([]); const redoStack = ref([]); const validation = ref([]); const definitionCode = ref(''); const suppressPortClick = ref(false)
let autoSaveTimer = null; let dragState = null; let panState = null
const stageWidth = 2400; const stageHeight = 1600; const rulerMarks = Array.from({ length: 24 }, (_, index) => index * 100)
const ports = ['top', 'right', 'bottom', 'left']
const isNewDefinition = computed(() => Boolean(props.definition?.isNew) || !definitionCode.value)

const filteredPalette = computed(() => palette.map(group => ({ ...group, items: group.items.filter(item => `${item.label}${item.description}`.toLowerCase().includes(paletteKeyword.value.toLowerCase())) })).filter(group => group.items.length))
const selectedNode = computed(() => nodes.value.find(node => node.id === selectedNodeId.value) || null)
const selectedEdge = computed(() => edges.value.find(edge => edge.id === selectedEdgeId.value) || null)
const hasValidationErrors = computed(() => validation.value.some(item => item.level === 'error'))
const saveStateClass = computed(() => saveState.value.includes('本地') ? 'local' : saveState.value.includes('中') ? 'saving' : dirty.value ? 'dirty' : 'saved')
const stageStyle = computed(() => ({ width: `${stageWidth}px`, height: `${stageHeight}px`, transform: `translate(${pan.x}px, ${pan.y}px) scale(${zoom.value})` }))
const definitionJson = computed(() => JSON.stringify({ process: { ...process }, nodes: nodes.value, edges: edges.value, variables: variables.value }, null, 2))
const miniViewportStyle = computed(() => ({ left: `${Math.max(0, -pan.x / stageWidth * 100)}%`, top: `${Math.max(0, -pan.y / stageHeight * 100)}%`, width: `${Math.min(100, (canvasViewport.value?.clientWidth || 800) / zoom.value / stageWidth * 100)}%`, height: `${Math.min(100, (canvasViewport.value?.clientHeight || 600) / zoom.value / stageHeight * 100)}%` }))

function nodeMeta(type) { const item = palette.flatMap(group => group.items).find(node => node.type === type); return item || { type, label: '节点', description: '', icon: '•', tone: 'blue' } }
function isGateway(type) { return ['exclusiveGateway', 'parallelGateway', 'inclusiveGateway'].includes(type) }
function nodeSubtitle(node) { if (node.type === 'userTask') return node.assigneeMode === 'user' ? node.assignee || '指定用户' : node.candidateGroups || '未配置候选人'; if (node.type === 'serviceTask') return node.serviceKey || '待配置服务'; if (isGateway(node.type)) return `${outgoingEdges(node.id).length} 条路径`; if (node.type === 'timerEvent') return node.timerValue || '待配置时间'; if (node.type === 'messageEvent') return node.messageName || '待配置消息'; return node.description || nodeMeta(node.type).description }
function nodeClasses(node) { return ['canvas-node', `node-${node.type}`, { selected: selectedNodeId.value === node.id, 'connect-source': connectingFrom.value?.id === node.id, 'canvas-connect-mode': canvasMode.value === 'connect' }] }
function nodeStyle(node) { const size = nodeSize(node); return { left: `${node.x}px`, top: `${node.y}px`, width: `${size.width}px`, minHeight: `${size.height}px` } }
function miniNodeStyle(node) { const size = nodeSize(node); return { left: `${node.x / stageWidth * 100}%`, top: `${node.y / stageHeight * 100}%`, width: `${Math.max(2, size.width / stageWidth * 100)}%`, height: `${Math.max(2, size.height / stageHeight * 100)}%` } }
function portClass(node) { return connectingFrom.value && connectingFrom.value.id !== node.id && node.type !== 'start' ? 'target-port' : 'source-port' }
function portDirection(port) { return port === 'right' ? '右侧' : port === 'left' ? '左侧' : port === 'top' ? '上方' : '下方' }
function portTitle(node, port) { if (connectingFrom.value && connectingFrom.value.id !== node.id && node.type !== 'start') return `连接到${node.label}的${portDirection(port)}连接点`; if (node.type === 'end') return `连接到${node.label}的${portDirection(port)}连接点`; return `从${node.label}向${portDirection(port)}连线` }
function edgePath(edge) { const fromNode = nodes.value.find(node => node.id === edge.source); const toNode = nodes.value.find(node => node.id === edge.target); if (!fromNode || !toNode) return ''; const selectedPorts = edge.sourcePort && edge.targetPort ? { sourcePort: edge.sourcePort, targetPort: edge.targetPort } : bestPorts(fromNode, toNode); return connectionPath(fromNode, toNode, selectedPorts.sourcePort, selectedPorts.targetPort) }
function edgeLabelPoint(edge) { const fromNode = nodes.value.find(node => node.id === edge.source); const toNode = nodes.value.find(node => node.id === edge.target); if (!fromNode || !toNode) return { x: 0, y: 0 }; const selectedPorts = edge.sourcePort && edge.targetPort ? { sourcePort: edge.sourcePort, targetPort: edge.targetPort } : bestPorts(fromNode, toNode); return connectionLabelPoint(fromNode, toNode, selectedPorts.sourcePort, selectedPorts.targetPort) }
const connectionPreviewPath = computed(() => connectingFrom.value ? buildConnectionPreviewPath(connectingFrom.value, connectionSourcePort.value, connectionCursor.value) : '')

function snapshot() { return JSON.parse(JSON.stringify({ process: { ...process }, nodes: nodes.value, edges: edges.value, variables: variables.value })) }
function restore(state) { Object.assign(process, state.process); nodes.value = state.nodes; edges.value = state.edges; variables.value = state.variables; selectedNodeId.value = nodes.value[0]?.id || ''; selectedEdgeId.value = ''; markDirty('恢复编辑快照', false) }
function perform(label, action) { undoStack.value.push(snapshot()); if (undoStack.value.length > 40) undoStack.value.shift(); redoStack.value = []; action(); markDirty(label) }
function undo() { if (!undoStack.value.length) return; redoStack.value.push(snapshot()); restore(undoStack.value.pop()); saveState.value = '未保存' }
function redo() { if (!redoStack.value.length) return; undoStack.value.push(snapshot()); restore(redoStack.value.pop()); saveState.value = '未保存' }
function markDirty(label = '字段变更', record = true) { dirty.value = true; saveState.value = '未保存'; if (record) history.value.unshift({ id: `${Date.now()}_${Math.random()}`, label, time: new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', second: '2-digit' }) }); scheduleAutoSave() }
function fieldChanged(label) { markDirty(label) }
function scheduleAutoSave() { window.clearTimeout(autoSaveTimer); autoSaveTimer = window.setTimeout(() => saveDesign(true), 1800) }

function selectNode(node) { if (connectingFrom.value && connectingFrom.value.id !== node.id) { finishConnection(node); return } selectedNodeId.value = node.id; selectedEdgeId.value = ''; if (canvasMode.value === 'connect' && node.type !== 'end') beginConnection(node, connectionSourcePort.value) }
function selectEdge(edge) { connectingFrom.value = null; selectedEdgeId.value = edge.id; selectedNodeId.value = '' }
function beginConnection(node, port = 'right') { selectedNodeId.value = node.id; selectedEdgeId.value = ''; connectingFrom.value = node; connectionSourcePort.value = port; connectionCursor.value = portPoint(node, port); canvasMode.value = 'connect'; saveState.value = '连接模式' }
function finishConnection(node, targetPort = null) { if (!connectingFrom.value || connectingFrom.value.id === node.id || node.type === 'start') return; const source = connectingFrom.value; const portsForEdge = targetPort ? { sourcePort: connectionSourcePort.value, targetPort } : bestPorts(source, node); const exists = edges.value.some(edge => edge.source === source.id && edge.target === node.id); if (!exists) perform(`新增连线：${source.label} → ${node.label}`, () => edges.value.push({ id: `edge_${Date.now()}`, source: source.id, target: node.id, sourcePort: portsForEdge.sourcePort, targetPort: portsForEdge.targetPort, condition: isGateway(source.type) ? '新分支' : '', expression: '', isDefault: false })); selectedNodeId.value = node.id; connectingFrom.value = null; canvasMode.value = 'select'; saveState.value = '未保存' }
function handlePortPointerDown(event, node, port) { suppressPortClick.value = false; if (connectingFrom.value && connectingFrom.value.id !== node.id && node.type !== 'start') return; if (!connectingFrom.value && node.type !== 'end') beginConnection(node, port) }
function handlePortPointerUp(event, node, port) { if (!connectingFrom.value || connectingFrom.value.id === node.id || node.type === 'start') return; finishConnection(node, port); suppressPortClick.value = true }
function handlePortClick(node, port) { if (suppressPortClick.value) { suppressPortClick.value = false; return } if (connectingFrom.value && connectingFrom.value.id !== node.id && node.type !== 'start') { finishConnection(node, port); return } if (!connectingFrom.value && node.type !== 'end') beginConnection(node, port) }
function handleViewportPointerDown(event) { if (event.target.closest?.('.canvas-node, .minimap') || ['path', 'text'].includes(event.target.tagName)) return; const canPan = canvasMode.value === 'pan' || event.button === 1 || spacePressed.value; if (canPan) { panState = { x: event.clientX, y: event.clientY, originX: pan.x, originY: pan.y }; isPanning.value = true; event.currentTarget?.setPointerCapture?.(event.pointerId); window.addEventListener('pointermove', movePan); window.addEventListener('pointerup', endPan, { once: true }); window.addEventListener('pointercancel', endPan, { once: true }) } else { selectedNodeId.value = ''; selectedEdgeId.value = ''; connectingFrom.value = null; canvasMode.value = 'select' } }
function movePan(event) { if (!panState) return; pan.x = panState.originX + event.clientX - panState.x; pan.y = panState.originY + event.clientY - panState.y }
function endPan() { panState = null; isPanning.value = false; window.removeEventListener('pointermove', movePan) }
function startNodeDrag(event, node) { if (event.button !== 0 || canvasMode.value === 'connect') return; selectedNodeId.value = node.id; selectedEdgeId.value = ''; dragState = { node, startX: event.clientX, startY: event.clientY, originX: node.x, originY: node.y, before: snapshot(), moved: false }; window.addEventListener('pointermove', moveNode); window.addEventListener('pointerup', endNodeDrag, { once: true }) }
function moveNode(event) { if (!dragState) return; const dx = (event.clientX - dragState.startX) / zoom.value; const dy = (event.clientY - dragState.startY) / zoom.value; if (Math.abs(dx) + Math.abs(dy) > 3) dragState.moved = true; dragState.node.x = Math.max(24, Math.round((dragState.originX + dx) / 10) * 10); dragState.node.y = Math.max(24, Math.round((dragState.originY + dy) / 10) * 10); if (connectingFrom.value) connectionCursor.value = { x: dragState.node.x, y: dragState.node.y } }
function endNodeDrag() { if (!dragState) return; if (dragState.moved) { undoStack.value.push(dragState.before); redoStack.value = []; markDirty(`移动节点：${dragState.node.label}`) } dragState = null; window.removeEventListener('pointermove', moveNode) }
function dragPalette(event, item) { event.dataTransfer?.setData('application/polaris-node', item.type); event.dataTransfer?.setData('text/plain', item.type); if (event.dataTransfer) event.dataTransfer.effectAllowed = 'copy' }
function canvasPoint(event) { const rect = canvasViewport.value?.getBoundingClientRect(); if (!rect) return { x: 320, y: 320 }; return { x: Math.max(24, (event.clientX - rect.left - pan.x) / zoom.value), y: Math.max(24, (event.clientY - rect.top - pan.y) / zoom.value) } }
function dropNode(event) { const type = event.dataTransfer?.getData('application/polaris-node') || event.dataTransfer?.getData('text/plain'); if (!type) return; const point = canvasPoint(event); addNodeAt(type, point.x - nodeSize({ type }).width / 2, point.y - 20) }
function addFromPalette(type) { addNodeAt(type, 260 + nodes.value.length * 18, 120 + (nodes.value.length % 4) * 110) }
function addNodeAt(type, x, y) { const node = baseNode(type, Math.round(x / 10) * 10, Math.round(y / 10) * 10, { code: `${type}_${nodes.value.length + 1}` }); perform(`新增节点：${nodeMeta(type).label}`, () => nodes.value.push(node)); selectedNodeId.value = node.id; selectedEdgeId.value = ''; runValidation(false); bottomPanel.value = '' }
function duplicateNode(node) { const copy = baseNode(node.type, node.x + 35, node.y + 35, { ...JSON.parse(JSON.stringify(node)), id: `${node.type}_${Date.now()}`, code: `${node.code}_copy`, label: `${node.label}（副本）` }); perform(`复制节点：${node.label}`, () => nodes.value.push(copy)); selectedNodeId.value = copy.id }
function removeNode(node) { if (!node) return; perform(`删除节点：${node.label}`, () => { nodes.value = nodes.value.filter(item => item.id !== node.id); edges.value = edges.value.filter(edge => edge.source !== node.id && edge.target !== node.id) }); selectedNodeId.value = ''; selectedEdgeId.value = '' }
function removeEdge(edge) { perform(`删除连线：${edge.source} → ${edge.target}`, () => { edges.value = edges.value.filter(item => item.id !== edge.id) }); selectedEdgeId.value = '' }
function outgoingEdges(id) { return edges.value.filter(edge => edge.source === id) }
function incomingEdges(id) { return edges.value.filter(edge => edge.target === id) }
function runValidation(openPanel = true) { validation.value = []; const add = (level, title, message, nodeId = '') => validation.value.push({ id: `${level}_${title}_${nodeId}`, level, title, message, nodeId }); const starts = nodes.value.filter(node => node.type === 'start'); const ends = nodes.value.filter(node => node.type === 'end'); if (!process.code.trim()) add('error', '流程编码不能为空', '请在流程属性中填写唯一的流程编码。'); if (!process.name.trim()) add('error', '流程名称不能为空', '请给当前流程填写一个便于业务识别的名称。'); if (starts.length !== 1) add('error', '开始事件数量不正确', `当前有 ${starts.length} 个开始事件，流程必须且只能有 1 个开始事件。`); if (!ends.length) add('error', '缺少结束事件', '至少配置一个结束事件，确保实例可以正常结束。'); const ids = new Set(); nodes.value.forEach(node => { if (ids.has(node.id)) add('error', '节点编码重复', `节点 ${node.label} 的 ID 重复，请重新生成。`, node.id); ids.add(node.id); if (node.type === 'userTask' && node.assigneeMode === 'group' && !node.candidateGroups?.trim()) add('error', '审批人未配置', `${node.label} 没有配置候选角色，运行时将无法生成待办。`, node.id); if (node.type === 'userTask' && node.assigneeMode === 'user' && !node.assignee?.trim()) add('error', '指定用户为空', `${node.label} 需要指定一个有效的用户编码。`, node.id); if (node.type === 'serviceTask' && !node.serviceKey?.trim()) add('error', '服务键未配置', `${node.label} 没有服务键，无法调用业务服务。`, node.id); if (isGateway(node.type) && outgoingEdges(node.id).length < 2) add('warning', '网关分支不足', `${node.label} 当前只有 ${outgoingEdges(node.id).length} 条出边，建议至少配置两条分支。`, node.id); if (node.type !== 'start' && !incomingEdges(node.id).length) add('warning', '节点未接入流程', `${node.label} 没有入边，运行时不会被触达。`, node.id); if (node.type !== 'end' && !outgoingEdges(node.id).length) add('warning', '节点没有后续路径', `${node.label} 没有出边，可能导致流程停留在此节点。`, node.id) }); edges.value.forEach(edge => { if (!nodes.value.some(node => node.id === edge.source) || !nodes.value.some(node => node.id === edge.target)) add('error', '存在无效连线', `连线 ${edge.id} 指向不存在的节点。`); if (edge.source === edge.target) add('error', '连线不能自循环', `连线 ${edge.id} 的起点和终点相同。`) }); if (openPanel) bottomPanel.value = 'validation'; saveState.value = validation.value.some(item => item.level === 'error') ? '待修复' : '已校验'; return validation.value }
function focusIssue(item) { if (item.nodeId) { selectedNodeId.value = item.nodeId; selectedEdgeId.value = ''; } }
function graphBounds() { if (!nodes.value.length) return { minX: 0, maxX: stageWidth, minY: 0, maxY: stageHeight }; return { minX: Math.min(...nodes.value.map(node => node.x)), maxX: Math.max(...nodes.value.map(node => node.x + nodeSize(node).width)), minY: Math.min(...nodes.value.map(node => node.y)), maxY: Math.max(...nodes.value.map(node => node.y + nodeSize(node).height)) } }
function fitCanvas() { if (!nodes.value.length) return; const bounds = graphBounds(); const viewport = canvasViewport.value; const availableWidth = viewport?.clientWidth || 900; const availableHeight = viewport?.clientHeight || 620; const padding = 96; zoom.value = Math.min(1.2, Math.max(0.45, Math.min((availableWidth - padding * 2) / Math.max(1, bounds.maxX - bounds.minX), (availableHeight - padding * 2) / Math.max(1, bounds.maxY - bounds.minY)))); centerCanvas() }
function centerCanvas() { const bounds = graphBounds(); const availableWidth = canvasViewport.value?.clientWidth || 900; const availableHeight = canvasViewport.value?.clientHeight || 620; pan.x = (availableWidth - (bounds.maxX - bounds.minX) * zoom.value) / 2 - bounds.minX * zoom.value; pan.y = (availableHeight - (bounds.maxY - bounds.minY) * zoom.value) / 2 - bounds.minY * zoom.value }
function zoomIn() { zoom.value = Math.min(2, Number((zoom.value + 0.1).toFixed(2))) }
function zoomOut() { zoom.value = Math.max(0.35, Number((zoom.value - 0.1).toFixed(2))) }
function zoomByWheel(event) { const rect = canvasViewport.value?.getBoundingClientRect(); if (!rect) return; const before = canvasPoint(event); const step = event.deltaY > 0 ? -0.06 : 0.06; const nextZoom = Math.min(2, Math.max(0.35, Number((zoom.value + step).toFixed(2)))); if (nextZoom === zoom.value) return; zoom.value = nextZoom; pan.x = event.clientX - rect.left - before.x * nextZoom; pan.y = event.clientY - rect.top - before.y * nextZoom }
function jumpToMiniMap(event) { const rect = event.currentTarget.getBoundingClientRect(); const worldX = ((event.clientX - rect.left) / rect.width) * stageWidth; const worldY = ((event.clientY - rect.top) / rect.height) * stageHeight; const viewport = canvasViewport.value; pan.x = (viewport?.clientWidth || 900) / 2 - worldX * zoom.value; pan.y = (viewport?.clientHeight || 620) / 2 - worldY * zoom.value }
function toggleBottomPanel(panel) { bottomPanel.value = bottomPanel.value === panel ? '' : panel }
function openProcessSettings() { selectedNodeId.value = ''; selectedEdgeId.value = ''; inspectorTab.value = 'properties' }
function addVariable() { perform('新增流程变量', () => variables.value.push({ id: `var_${Date.now()}`, key: '', label: '', type: 'string', defaultValue: '' })); inspectorTab.value = 'variables' }
function removeVariable(variable) { perform(`删除流程变量：${variable.key || '未命名'}`, () => { variables.value = variables.value.filter(item => item.id !== variable.id) }) }
async function copyJson() { try { await navigator.clipboard.writeText(definitionJson.value); saveState.value = 'JSON 已复制' } catch { saveState.value = '复制失败' } }

function storageKey(code = process.code) { return `polaris-bpm-design:${code}` }
function applyDesign(data) { const design = data?.design || data; if (!design || !Array.isArray(design.nodes)) return false; Object.assign(process, { ...defaultProcess, ...(design.process || {}), processType: design.process?.processType || design.processType || process.processType, triggerType: design.process?.triggerType || design.triggerType || process.triggerType, code: design.process?.code || design.processCode || process.code, name: design.process?.name || design.processName || process.name }); nodes.value = design.nodes.map(node => ({ ...nodeDefaults(node.type), ...node })); edges.value = Array.isArray(design.edges) ? design.edges : []; variables.value = Array.isArray(design.variables) ? design.variables : []; definitionCode.value = process.code; dirty.value = false; saveState.value = '已保存'; validation.value = []; return true }
async function loadDesign() { const definition = props.definition || {}; const code = definition.process_code || definition.processCode || definition.code || (definition.isNew ? process.code : 'workOrderApproval'); definitionCode.value = definition.isNew ? '' : code; Object.assign(process, { ...defaultProcess, code, name: definition.process_name || definition.processName || (definition.isNew ? '新业务流程' : defaultProcess.name), processType: definition.process_type || definition.processType || (definition.isNew ? 'BUSINESS' : defaultProcess.processType), triggerType: definition.trigger_type || definition.triggerType || 'MANUAL', category: definition.category || (definition.isNew ? '通用业务' : defaultProcess.category), version: Number(definition.version || 1) }); if (definition.isNew) { nodes.value = createDefaultNodes(); edges.value = createDefaultEdges(); variables.value = []; validation.value = []; dirty.value = true; saveState.value = '未保存'; window.setTimeout(fitCanvas, 80); return } const remote = await request(`/bpm/process-designs/${encodeURIComponent(code)}`); let localData = null; try { const local = localStorage.getItem(storageKey(code)); localData = local ? JSON.parse(local) : null } catch { localData = null } if (!applyDesign(remote) && !(localData && applyDesign(localData))) { nodes.value = createDefaultNodes(); edges.value = createDefaultEdges(); validation.value = []; dirty.value = true; saveState.value = '未保存' } window.setTimeout(fitCanvas, 80) }
async function saveDesign(auto = false) { if (saving.value) return; saving.value = true; saveState.value = auto ? '自动保存中' : '保存中'; const body = { processCode: process.code, processName: process.name, description: process.description, category: process.category, processType: process.processType, triggerType: process.triggerType, owner: process.owner, version: process.version, process: { ...process }, nodes: nodes.value, edges: edges.value, variables: variables.value, status: 'DRAFT' }; try { await request(`/bpm/process-designs/${encodeURIComponent(process.code)}`, { method: 'PUT', body: JSON.stringify(body), allowFallback: false }); definitionCode.value = process.code; localStorage.setItem(storageKey(), JSON.stringify(body)); saveState.value = '已保存'; dirty.value = false } catch (error) { localStorage.setItem(storageKey(), JSON.stringify(body)); saveState.value = '保存失败（已保留本地副本）'; if (!auto) console.error(error) } finally { saving.value = false } }
async function publishDesign() { runValidation(); if (hasValidationErrors.value) { saveState.value = '待修复'; return } const body = { processCode: process.code, processName: process.name, description: process.description, category: process.category, processType: process.processType, triggerType: process.triggerType, owner: process.owner, version: process.version, process: { ...process }, nodes: nodes.value, edges: edges.value, variables: variables.value, status: 'PUBLISHED' }; saving.value = true; saveState.value = '发布中'; try { await request(`/bpm/process-designs/${encodeURIComponent(process.code)}/publish`, { method: 'POST', body: JSON.stringify(body), allowFallback: false }); definitionCode.value = process.code; localStorage.setItem(storageKey(), JSON.stringify(body)); saveState.value = '已发布'; dirty.value = false } catch (error) { saveState.value = '发布失败'; console.error(error) } finally { saving.value = false } }
function onKeydown(event) { const tag = document.activeElement?.tagName; if (event.code === 'Space' && !['INPUT', 'TEXTAREA', 'SELECT'].includes(tag)) { spacePressed.value = true; event.preventDefault() } if (!['INPUT', 'TEXTAREA', 'SELECT'].includes(tag) && event.key.toLowerCase() === 'c') { canvasMode.value = 'connect'; event.preventDefault() } if (!['INPUT', 'TEXTAREA', 'SELECT'].includes(tag) && event.key.toLowerCase() === 'v') { canvasMode.value = 'select'; connectingFrom.value = null; event.preventDefault() } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 's') { event.preventDefault(); saveDesign(false) } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'z' && tag !== 'INPUT' && tag !== 'TEXTAREA') { event.preventDefault(); event.shiftKey ? redo() : undo() } if (event.key === 'Escape') { connectingFrom.value = null; canvasMode.value = 'select'; if (showPreview.value) showPreview.value = false } if ((event.key === 'Delete' || event.key === 'Backspace') && !['INPUT', 'TEXTAREA', 'SELECT'].includes(tag)) { if (selectedNode.value) removeNode(selectedNode.value); else if (selectedEdge.value) removeEdge(selectedEdge.value) } }
function onKeyup(event) { if (event.code === 'Space') spacePressed.value = false }

function trackConnection(event) { if (connectingFrom.value && canvasViewport.value) connectionCursor.value = canvasPoint(event) }
watch(() => props.definition, loadDesign, { immediate: true })
onMounted(() => { window.addEventListener('keydown', onKeydown); window.addEventListener('keyup', onKeyup); window.addEventListener('pointermove', trackConnection); window.setTimeout(() => runValidation(false), 120) })
onBeforeUnmount(() => { window.clearTimeout(autoSaveTimer); window.removeEventListener('keydown', onKeydown); window.removeEventListener('keyup', onKeyup); window.removeEventListener('pointermove', trackConnection); window.removeEventListener('pointermove', moveNode); window.removeEventListener('pointermove', movePan) })
</script>
