<template>
  <PageShell :title="tabTitle" description="以当前租户为边界维护账号、角色、菜单、字典和租户运行参数。">
    <template #actions>
      <button class="button button-ghost" :disabled="loading" @click="load">↻ 刷新</button>
      <button v-if="canEdit && ['users', 'roles', 'menus', 'dictionaries'].includes(tab)" class="button button-primary" @click="openCreate">+ {{ createLabel }}</button>
    </template>

    <div class="subnav">
      <button v-for="item in tabs" :key="item.key" :class="['subnav-item', { active: tab === item.key }]" @click="switchTab(item.key)">{{ item.label }}</button>
    </div>
    <div v-if="notice" :class="['notice-bar', `notice-${notice.type}`]" role="status"><span>{{ notice.type === 'error' ? '!' : '✓' }}</span>{{ notice.message }}</div>

    <div v-if="tab === 'users'" class="panel">
      <div class="admin-kpis"><div><span>用户总数</span><b>{{ users.length }}</b></div><div><span>已启用</span><b class="text-success">{{ activeUsers }}</b></div><div><span>角色数量</span><b>{{ roles.length }}</b></div><div><span>最近登录</span><b>{{ recentlyLoggedIn }}</b></div></div>
      <div class="filter-row"><input v-model="keyword" placeholder="搜索用户名 / 姓名 / 角色" /><DictSelect v-model="statusFilter" type="COMMON_STATUS" placeholder="全部状态" /><span class="filter-spacer"></span><span class="data-hint">数据范围：当前租户 · {{ tenantCode }}</span></div>
      <DataTable :columns="userColumns" :rows="filteredUsers" :loading="loading" :show-toolbar="true" :enable-export="true" :enable-column-settings="true" :pagination="true" table-title="用户列表" table-hint="账号、角色和状态均按当前租户隔离" export-name="polaris-users">
        <template #actions="{ row }"><button class="table-action" @click="openEdit(row)">编辑</button><button class="table-action" @click="openReset(row)">重置密码</button><button class="table-action" @click="toggleUser(row)">{{ row.status ? '停用' : '启用' }}</button></template>
      </DataTable>
    </div>

    <div v-else-if="tab === 'roles'" class="permission-layout">
      <div class="panel permission-tree">
        <div class="panel-heading"><div><h3>角色定义</h3><p>新增、编辑、启停和删除角色</p></div></div>
        <button v-for="role in roles" :key="role.role_code" :class="['role-row', { active: selectedRole === role.role_code }]" @click="selectRole(role.role_code)"><span class="role-avatar">{{ role.role_name.slice(0, 1) }}</span><span><b>{{ role.role_name }}</b><small>{{ role.role_code }} · {{ role.description || '未填写说明' }}</small></span><strong>{{ permissionCount(role.role_code) }}</strong></button>
        <div v-if="!roles.length" class="empty-operation">暂无角色数据</div>
      </div>
      <div class="panel permission-editor">
        <div class="panel-heading"><div><h3>{{ selectedRoleName }} · 权限矩阵</h3><p>菜单权限和按钮动作统一写入 sys_permission</p></div><div class="inline-actions"><button v-if="canEdit" class="button button-ghost" @click="openRoleEdit(selectedRoleObject)">编辑角色</button><button v-if="canEdit && selectedRole !== 'admin'" class="button button-ghost danger-button" @click="removeRole(selectedRoleObject)">删除角色</button><button v-if="canEdit" class="button button-primary" :disabled="saving" @click="savePermissions">保存权限</button></div></div>
        <div class="permission-toolbar"><span>已选 {{ selectedPermissionCount }} 项</span><button class="text-button" @click="selectAllPermissions">全选当前资源</button><button class="text-button" @click="clearPermissions">清空</button></div>
        <div class="permission-grid"><div v-for="menu in menuRows" :key="menu.id" class="permission-grid-row"><div class="permission-resource" :style="{ paddingLeft: `${menu.level * 18 + 8}px` }"><span>{{ menu.level ? '↳' : '▣' }}</span><b>{{ menu.menu_name }}</b><small>{{ menu.menu_code }}</small></div><label v-for="action in actions" :key="`${menu.menu_code}-${action.code}`" class="permission-check"><input v-model="permissionKeys" type="checkbox" :value="permissionKey(menu, action)" /><span>{{ action.label }}</span></label></div><div v-if="!menuRows.length" class="empty-operation">暂无菜单，请先维护菜单树</div></div>
      </div>
    </div>

    <div v-else-if="tab === 'menus'" class="panel">
      <div class="panel-heading"><div><h3>菜单树</h3><p>菜单节点、路由和排序持久化到当前租户数据库；删除父节点前需先处理子节点。</p></div><span class="status-pill status-released">数据库维护</span></div>
      <DataTable :columns="menuColumns" :rows="menuRows" :loading="loading" :show-toolbar="true" :pagination="true" table-title="菜单结构" table-hint="树形层级 · 路由 · 显示状态" export-name="polaris-menus">
        <template #cell-menu_name="{ row }"><span :style="{ paddingLeft: `${row.level * 22}px` }" class="menu-tree-label"><i>{{ row.level ? '└' : '▣' }}</i><b>{{ row.menu_name }}</b></span></template>
        <template #actions="{ row }"><button v-if="canEdit" class="table-action" @click="openMenuEdit(row)">编辑</button><button v-if="canEdit" class="table-action" @click="openMenuChild(row)">新增子菜单</button><button v-if="canEdit" class="table-action danger-link" @click="removeMenu(row)">删除</button></template>
      </DataTable>
    </div>

    <div v-else-if="tab === 'tenants'" class="tenant-admin-grid">
      <div class="panel tenant-profile-card"><div class="panel-heading"><div><h3>当前租户配置</h3><p>租户管理员只维护自己的企业资料与套餐参数</p></div><span class="status-pill status-released">租户隔离已启用</span></div><div class="tenant-identity"><div class="tenant-logo">{{ tenantForm.tenantName?.slice(0, 1) || 'P' }}</div><div><b>{{ tenantForm.tenantName || '当前租户' }}</b><small>{{ tenantForm.tenantCode }} · {{ tenantForm.planCode }}</small></div></div><DynamicForm v-model="tenantForm" :schema="tenantSchema" :columns="2" /><div class="tenant-boundary"><b>数据边界</b><span>业务表、配置表、审计日志均通过 token 绑定 tenant_id；平台级运维如需跨租户操作，应另设平台运营角色和审计入口。</span></div><div class="modal-actions"><button class="button button-primary" :disabled="saving" @click="saveTenant">{{ saving ? '保存中…' : '保存租户配置' }}</button></div></div>
      <div class="panel"><div class="panel-heading"><div><h3>租户运行概览</h3><p>用于后续 SaaS 套餐、配额和到期策略</p></div></div><div class="tenant-stat-list"><div><span>订阅方案</span><b>{{ tenantForm.planCode || '-' }}</b></div><div><span>用户上限</span><b>{{ tenantForm.maxUsers || 0 }}</b></div><div><span>已用用户</span><b>{{ tenantForm.user_count || 0 }}</b></div><div><span>试用截止</span><b>{{ formatDate(tenantForm.trial_ends_at) }}</b></div><div><span>租户状态</span><b class="text-success">{{ tenantForm.status ? '运行中' : '已停用' }}</b></div></div><div class="callout">建议的未来演进：平台运营端维护租户生命周期；租户管理员维护本租户资料、用户、角色和业务字典；所有跨租户行为必须走独立的运营权限与审计链路。</div></div>
    </div>

    <div v-else-if="tab === 'dictionaries'" class="dictionary-layout">
      <div class="panel dictionary-types"><div class="panel-heading"><div><h3>字典目录</h3><p>字典类型作为树根，字典项可继续挂载父节点</p></div></div><button v-for="type in dictionaryTypes" :key="type.type" :class="['dictionary-type-row', { active: dictionaryType === type.type }]" @click="dictionaryType = type.type; loadDictionary()"><span>▾</span><b>{{ type.type }}</b><small>{{ type.count }} 项</small></button><div v-if="!dictionaryTypes.length" class="empty-operation">暂无字典类型</div></div>
      <div class="panel"><div class="panel-heading"><div><h3>{{ dictionaryType || '字典项' }}</h3><p>支持增删改查、启停和层级维护</p></div><button v-if="canEdit" class="button button-primary" @click="openDictionaryCreate">+ 新增字典项</button></div><DataTable :columns="dictionaryColumns" :rows="dictionaryTreeRows" :loading="loading" :show-toolbar="true" :enable-export="true" :pagination="true" table-title="字典项" table-hint="停用项仍保留在维护端，不会返回给业务选择框" export-name="polaris-dictionaries"><template #cell-label="{ row }"><span :style="{ paddingLeft: `${row.level * 20}px` }" class="menu-tree-label"><i>{{ row.level ? '└' : '•' }}</i>{{ row.label }}</span></template><template #cell-status="{ row }"><span :class="['status-pill', row.status ? 'status-released' : 'status-planned']">{{ row.status ? '启用' : '停用' }}</span></template><template #actions="{ row }"><button v-if="canEdit" class="table-action" @click="openDictionaryEdit(row)">编辑</button><button v-if="canEdit" class="table-action" @click="removeDictionary(row)">删除</button></template></DataTable></div>
    </div>

    <div v-else class="panel audit-panel"><div class="panel-heading"><div><h3>操作审计</h3><p>记录当前租户的写入动作，便于追责、排障与合规检查</p></div><span class="status-pill status-released">服务端实时记录</span></div><div class="filter-row"><input v-model="auditKeyword" placeholder="搜索操作人、接口或动作" @keyup.enter="loadAudit" /><button class="button button-ghost" @click="loadAudit">查询</button><span class="filter-spacer"></span><span class="data-hint">共 {{ auditTotal }} 条记录</span></div><DataTable :columns="auditColumns" :rows="auditRows" :loading="loading" /><div class="audit-pagination"><span>第 {{ auditPage }} 页</span><button class="button button-ghost" :disabled="auditPage <= 1 || loading" @click="auditPage--; loadAudit()">上一页</button><button class="button button-ghost" :disabled="auditPage * auditSize >= auditTotal || loading" @click="auditPage++; loadAudit()">下一页</button></div></div>

    <AppModal v-model="showUserModal" :title="editingUser ? '编辑用户' : '新增用户'" subtitle="账号、角色和状态保存后立即对后续请求生效" :loading="saving" confirm-text="保存用户" @confirm="saveUser"><DynamicForm v-model="userForm" :schema="userFormSchema" :columns="2" /></AppModal>
    <AppModal v-model="showPasswordModal" title="重置登录密码" :subtitle="`账号：${resetTarget?.username || '-'}`" :loading="saving" confirm-text="确认重置" @confirm="resetPassword"><DynamicForm v-model="resetForm" :schema="resetFormSchema" /></AppModal>
    <AppModal v-model="showRoleModal" :title="editingRole ? '编辑角色' : '新增角色'" :loading="saving" confirm-text="保存角色" @confirm="saveRole"><DynamicForm v-model="roleForm" :schema="roleSchema" :columns="2" /></AppModal>
    <AppModal v-model="showMenuModal" :title="editingMenu ? '编辑菜单' : '新增菜单'" :loading="saving" confirm-text="保存菜单" @confirm="saveMenu"><DynamicForm v-model="menuForm" :schema="menuSchema" :columns="2" /></AppModal>
    <AppModal v-model="showDictionaryModal" :title="editingDictionary ? '编辑字典项' : '新增字典项'" :loading="saving" confirm-text="保存字典项" @confirm="saveDictionary"><DynamicForm v-model="dictionaryForm" :schema="dictionarySchema" :columns="2" /></AppModal>
  </PageShell>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import PageShell from '../components/PageShell.vue'
import DataTable from '../components/DataTable.vue'
import AppModal from '../components/AppModal.vue'
import DynamicForm from '../components/DynamicForm.vue'
import DictSelect from '../components/DictSelect.vue'
import { request } from '../api'

const route = useRoute(); const router = useRouter()
const rawTab = route.params.tab || 'users'; const tab = ref(rawTab === 'permissions' ? 'roles' : rawTab)
const loading = ref(false); const saving = ref(false); const notice = ref(null)
const users = ref([]); const roles = ref([]); const menus = ref([]); const permissions = ref([]); const permissionKeys = ref([]); const selectedRole = ref('admin')
const dictionaryTypes = ref([]); const dictionaryType = ref(''); const dictionaryRows = ref([]); const tenantForm = ref({}); const auditRows = ref([]); const auditTotal = ref(0); const auditPage = ref(1); const auditSize = 20; const auditKeyword = ref('')
const keyword = ref(''); const statusFilter = ref(''); const editingUser = ref(null); const resetTarget = ref(null); const editingRole = ref(null); const selectedMenuParent = ref(null); const editingMenu = ref(null); const editingDictionary = ref(null)
const showUserModal = ref(false); const showPasswordModal = ref(false); const showRoleModal = ref(false); const showMenuModal = ref(false); const showDictionaryModal = ref(false)
const userForm = ref({}); const resetForm = ref({ password: '' }); const roleForm = ref({}); const menuForm = ref({}); const dictionaryForm = ref({})
const tabs = [{ key: 'users', label: '用户' }, { key: 'roles', label: '角色与权限' }, { key: 'menus', label: '菜单维护' }, { key: 'tenants', label: '租户维护' }, { key: 'dictionaries', label: '字典配置' }, { key: 'audit', label: '操作审计' }]
const actions = [{ code: 'VIEW', label: '查看' }, { code: 'CREATE', label: '新增' }, { code: 'UPDATE', label: '编辑' }, { code: 'DELETE', label: '删除' }, { code: 'EXPORT', label: '导出' }]
const canEdit = computed(() => { try { return JSON.parse(localStorage.getItem('polaris-user') || '{}').roleCode === 'admin' } catch { return false } })
const tabTitle = computed(() => tabs.find(item => item.key === tab.value)?.label || '系统管理'); const createLabel = computed(() => ({ users: '用户', roles: '角色', menus: '菜单', dictionaries: '字典项' }[tab.value] || '配置'))
const tenantCode = computed(() => { try { return JSON.parse(localStorage.getItem('polaris-tenant') || '{}').code || '当前租户' } catch { return '当前租户' } })
const activeUsers = computed(() => users.value.filter(item => item.status).length); const recentlyLoggedIn = computed(() => users.value.filter(item => item.last_login_at).length)
const roleByCode = code => roles.value.find(item => item.role_code === code); const selectedRoleObject = computed(() => roleByCode(selectedRole.value) || {})
const selectedRoleName = computed(() => selectedRoleObject.value.role_name || selectedRole.value); const filteredUsers = computed(() => users.value.filter(item => (!statusFilter.value || (statusFilter.value === 'ACTIVE' ? Boolean(item.status) : !item.status)) && (!keyword.value || `${item.username}${item.display_name}${item.role_code}${roleName(item.role_code)}`.toLowerCase().includes(keyword.value.toLowerCase()))))
const menuRows = computed(() => flattenMenus(menus.value)); const dictionaryTreeRows = computed(() => flattenDictionary(dictionaryRows.value)); const selectedPermissionCount = computed(() => permissionKeys.value.length)
const userColumns = [{ key: 'username', label: '用户名' }, { key: 'display_name', label: '姓名' }, { key: 'role_code', label: '角色', format: value => roleName(value) }, { key: 'last_login_at', label: '最近登录', format: formatDate }, { key: 'status', label: '状态', status: true, format: value => value ? '已启用' : '已停用' }]
const menuColumns = [{ key: 'menu_name', label: '菜单名称' }, { key: 'menu_code', label: '编码' }, { key: 'menu_type', label: '类型' }, { key: 'route_path', label: '路由' }, { key: 'sort_no', label: '排序' }, { key: 'visible', label: '可见', format: value => value ? '是' : '否' }]
const dictionaryColumns = [{ key: 'code', label: '编码' }, { key: 'label', label: '显示名称' }, { key: 'value', label: '实际值' }, { key: 'locale', label: '语言' }, { key: 'sortNo', label: '排序' }, { key: 'status', label: '状态' }]
const auditColumns = [{ key: 'created_at', label: '时间', format: formatDate }, { key: 'actor', label: '操作人' }, { key: 'action_code', label: '动作' }, { key: 'request_uri', label: '接口' }, { key: 'resource_type', label: '资源类型' }]
const userFormSchema = computed(() => [{ key: 'username', label: '用户名', required: !editingUser.value, disabled: Boolean(editingUser.value) }, { key: 'displayName', label: '姓名', required: true }, { key: 'roleCode', label: '角色', type: 'select', options: roles.value.map(item => ({ value: item.role_code, label: `${item.role_name}（${item.role_code}）` })), required: true }, ...(editingUser.value ? [{ key: 'status', label: '账号状态', type: 'select', options: [{ value: 1, label: '已启用' }, { value: 0, label: '已停用' }] }] : [{ key: 'password', label: '初始密码', type: 'password', required: true }])])
const resetFormSchema = [{ key: 'password', label: '新密码', type: 'password', required: true }]; const roleSchema = [{ key: 'roleCode', label: '角色编码', required: true, disabled: Boolean(editingRole.value) }, { key: 'roleName', label: '角色名称', required: true }, { key: 'description', label: '角色说明' }, { key: 'status', label: '状态', type: 'select', options: [{ value: 1, label: '启用' }, { value: 0, label: '停用' }] }]
const menuSchema = computed(() => [{ key: 'parentId', label: '上级菜单', type: 'select', options: [{ value: 0, label: '根菜单' }, ...menuRows.value.filter(item => item.id !== editingMenu.value?.id).map(item => ({ value: item.id, label: `${'　'.repeat(item.level)}${item.menu_name}` }))] }, { key: 'menuCode', label: '菜单编码', required: true, disabled: Boolean(editingMenu.value) }, { key: 'menuName', label: '菜单名称', required: true }, { key: 'menuType', label: '类型', type: 'select', options: [{ value: 'GROUP', label: '分组' }, { value: 'MENU', label: '页面菜单' }, { value: 'BUTTON', label: '按钮' }] }, { key: 'routePath', label: '路由地址' }, { key: 'icon', label: '图标编码' }, { key: 'sortNo', label: '排序号', type: 'number' }, { key: 'visible', label: '是否显示', type: 'select', options: [{ value: 1, label: '显示' }, { value: 0, label: '隐藏' }] }])
const dictionarySchema = computed(() => [{ key: 'type', label: '字典类型', required: true }, { key: 'parentId', label: '父节点', type: 'select', options: [{ value: 0, label: '当前类型根节点' }, ...dictionaryRows.value.filter(item => item.id !== editingDictionary.value?.id).map(item => ({ value: item.id, label: `${'　'.repeat(item.level || 0)}${item.label}` }))] }, { key: 'code', label: '编码', required: true }, { key: 'label', label: '显示名称', required: true }, { key: 'value', label: '实际值', required: true }, { key: 'locale', label: '语言', type: 'select', options: [{ value: 'zh-CN', label: '中文' }, { value: 'en-US', label: 'English' }] }, { key: 'sortNo', label: '排序号', type: 'number' }, { key: 'status', label: '状态', type: 'select', options: [{ value: 1, label: '启用' }, { value: 0, label: '停用' }] }])
const tenantSchema = [{ key: 'tenantName', label: '企业名称', required: true }, { key: 'contactName', label: '联系人' }, { key: 'contactEmail', label: '联系邮箱' }, { key: 'maxUsers', label: '用户上限', type: 'number' }]

function roleName(code) { return roleByCode(code)?.role_name || code || '-' }; function formatDate(value) { return value ? String(value).replace('T', ' ').slice(0, 16) : '-' }; function showNotice(message, type = 'success') { notice.value = { message, type }; window.clearTimeout(showNotice.timer); showNotice.timer = window.setTimeout(() => notice.value = null, 3600) }
function flattenMenus(rows, parentId = 0, level = 0, result = []) { rows.filter(item => Number(item.parent_id || 0) === Number(parentId)).forEach(item => { result.push({ ...item, level }); flattenMenus(rows, item.id, level + 1, result) }); return result }
function flattenDictionary(rows, parentId = 0, level = 0, result = []) { rows.filter(item => Number(item.parentId || 0) === Number(parentId)).forEach(item => { result.push({ ...item, level }); flattenDictionary(rows, item.id, level + 1, result) }); return result }
function permissionKey(menu, action) { return `${menu.menu_code}:${action.code}` }; function permissionCount(code) { return code === selectedRole.value ? permissionKeys.value.length : permissions.value.filter(item => item.role_code === code).length }
function switchTab(value) { tab.value = value; router.push(`/admin/${value}`); load() }; function selectRole(value) { selectedRole.value = value; loadPermissions() }
function openCreate() { if (tab.value === 'users') openUserCreate(); else if (tab.value === 'roles') openRoleCreate(); else if (tab.value === 'menus') openMenuCreate(); else openDictionaryCreate() }
function openUserCreate() { editingUser.value = null; userForm.value = { username: '', displayName: '', roleCode: roles.value[0]?.role_code || 'operator', password: '', status: 1 }; showUserModal.value = true }
function openEdit(row) { editingUser.value = row; userForm.value = { username: row.username, displayName: row.display_name, roleCode: row.role_code, status: Number(row.status) }; showUserModal.value = true }
function openReset(row) { resetTarget.value = row; resetForm.value = { password: '' }; showPasswordModal.value = true }
function openRoleCreate() { editingRole.value = null; roleForm.value = { roleCode: '', roleName: '', description: '', status: 1 }; showRoleModal.value = true }; function openRoleEdit(row) { if (!row?.id) return; editingRole.value = row; roleForm.value = { roleCode: row.role_code, roleName: row.role_name, description: row.description || '', status: Number(row.status) }; showRoleModal.value = true }
function openMenuCreate() { editingMenu.value = null; menuForm.value = { parentId: 0, menuCode: '', menuName: '', menuType: 'MENU', routePath: '', icon: 'grid', sortNo: 99, visible: 1 }; showMenuModal.value = true }; function openMenuChild(row) { editingMenu.value = null; menuForm.value = { parentId: row.id, menuCode: '', menuName: '', menuType: 'MENU', routePath: '', icon: 'grid', sortNo: 99, visible: 1 }; showMenuModal.value = true }; function openMenuEdit(row) { editingMenu.value = row; menuForm.value = { ...row, parentId: row.parent_id, menuCode: row.menu_code, menuName: row.menu_name, menuType: row.menu_type, routePath: row.route_path, sortNo: row.sort_no, visible: Number(row.visible) }; showMenuModal.value = true }
function openDictionaryCreate() { editingDictionary.value = null; dictionaryForm.value = { type: dictionaryType.value || dictionaryTypes.value[0]?.type || 'BUSINESS_STATUS', parentId: 0, code: '', label: '', value: '', locale: 'zh-CN', sortNo: 99, status: 1 }; showDictionaryModal.value = true }; function openDictionaryEdit(row) { editingDictionary.value = row; dictionaryForm.value = { ...row, type: row.type || dictionaryType.value }; showDictionaryModal.value = true }
function selectAllPermissions() { permissionKeys.value = menuRows.value.flatMap(menu => actions.map(action => permissionKey(menu, action))) }; function clearPermissions() { permissionKeys.value = [] }

async function load() { loading.value = true; try { if (tab.value === 'audit') return await loadAudit(); if (tab.value === 'tenants') return await loadTenant(); if (tab.value === 'dictionaries') return await loadDictionaryTypes(); const [userData, roleData, menuData] = await Promise.all([request('/admin/users'), request('/admin/roles'), request('/menus/tree')]); users.value = userData || []; roles.value = roleData || []; menus.value = menuData || []; if (!roles.value.some(item => item.role_code === selectedRole.value)) selectedRole.value = roles.value[0]?.role_code || 'admin'; await loadPermissions() } catch (error) { showNotice(error.message, 'error') } finally { loading.value = false } }
async function loadPermissions() { permissions.value = await request(`/admin/permissions?roleCode=${encodeURIComponent(selectedRole.value)}`) || []; const wildcard = permissions.value.some(item => item.resource_type === 'MENU' && item.resource_code === '*' && item.action_code === '*'); permissionKeys.value = wildcard ? menuRows.value.flatMap(menu => actions.map(action => permissionKey(menu, action))) : permissions.value.filter(item => item.resource_type === 'MENU').map(item => `${item.resource_code}:${item.action_code}`) }
async function loadDictionaryTypes() { const types = await request('/dictionaries?locale=zh-CN') || []; dictionaryTypes.value = await Promise.all(types.map(async item => ({ ...item, count: (await request(`/dictionaries/${encodeURIComponent(item.type)}?includeDisabled=true`)).length }))); if (!dictionaryType.value || !dictionaryTypes.value.some(item => item.type === dictionaryType.value)) dictionaryType.value = dictionaryTypes.value[0]?.type || ''; if (dictionaryType.value) dictionaryRows.value = await request(`/dictionaries/${encodeURIComponent(dictionaryType.value)}?includeDisabled=true`) || [] }
async function loadDictionary() { loading.value = true; try { dictionaryRows.value = await request(`/dictionaries/${encodeURIComponent(dictionaryType.value)}?includeDisabled=true`) || [] } catch (error) { showNotice(error.message, 'error') } finally { loading.value = false } }
async function loadTenant() { tenantForm.value = await request('/tenant/profile') || {} }
async function loadAudit() { const data = await request(`/admin/audit-logs?keyword=${encodeURIComponent(auditKeyword.value)}&page=${auditPage.value}&size=${auditSize}`); auditRows.value = data?.items || []; auditTotal.value = Number(data?.total || 0) }
async function saveUser() { if (!userForm.value.displayName || !userForm.value.roleCode || (!editingUser.value && (!userForm.value.username || userForm.value.password?.length < 8))) return showNotice('请完整填写用户信息，初始密码至少 8 位', 'warning'); await saveRequest(editingUser.value ? `/admin/users/${editingUser.value.id}` : '/admin/users', editingUser.value ? 'PUT' : 'POST', userForm.value, editingUser.value ? '用户已更新' : '用户已创建', showUserModal, load) }
async function resetPassword() { if ((resetForm.value.password || '').length < 8) return showNotice('新密码至少需要 8 位', 'warning'); await saveRequest(`/admin/users/${resetTarget.value.id}/reset-password`, 'POST', resetForm.value, '密码已重置', showPasswordModal) }
async function toggleUser(row) { await saveRequest(`/admin/users/${row.id}`, 'PUT', { displayName: row.display_name, roleCode: row.role_code, status: row.status ? 0 : 1 }, row.status ? '用户已停用' : '用户已启用', null, load) }
async function saveRole() { await saveRequest(editingRole.value ? `/admin/roles/${editingRole.value.id}` : '/admin/roles', editingRole.value ? 'PUT' : 'POST', roleForm.value, '角色已保存', showRoleModal, load) }
async function removeRole(row) { if (!row?.id || !window.confirm(`确认删除角色“${row.role_name}”？`)) return; await saveRequest(`/admin/roles/${row.id}`, 'DELETE', null, '角色已删除', null, load) }
async function savePermissions() { const payload = permissionKeys.value.map(key => { const [resourceCode, actionCode] = key.split(':'); return { resourceType: 'MENU', resourceCode, actionCode, effect: 'ALLOW', fieldMaskJson: '{}' } }); await saveRequest(`/admin/roles/${encodeURIComponent(selectedRole.value)}/permissions`, 'PUT', payload, '角色权限已保存', null, loadPermissions) }
async function saveMenu() { await saveRequest(editingMenu.value ? `/menus/${editingMenu.value.id}` : '/menus', editingMenu.value ? 'PUT' : 'POST', menuForm.value, '菜单已保存', showMenuModal, load) }
async function removeMenu(row) { if (!window.confirm(`确认删除菜单“${row.menu_name}”？`)) return; await saveRequest(`/menus/${row.id}`, 'DELETE', null, '菜单已删除', null, load) }
async function saveDictionary() { await saveRequest(editingDictionary.value ? `/dictionaries/${editingDictionary.value.id}` : '/dictionaries', editingDictionary.value ? 'PUT' : 'POST', dictionaryForm.value, '字典项已保存', showDictionaryModal, loadDictionaryTypes) }
async function removeDictionary(row) { if (!window.confirm(`确认删除字典项“${row.label}”？`)) return; await saveRequest(`/dictionaries/${row.id}`, 'DELETE', null, '字典项已删除', null, loadDictionaryTypes) }
async function saveTenant() { await saveRequest('/tenant/profile', 'PUT', tenantForm.value, '租户配置已保存', null, loadTenant) }
async function saveRequest(path, method, body, message, modal, after) { saving.value = true; try { await request(path, { method, ...(body === null ? {} : { body: JSON.stringify(body) }) }); if (modal) modal.value = false; showNotice(message); if (after) await after() } catch (error) { showNotice(error.message, 'error') } finally { saving.value = false } }
onMounted(load)
</script>
