package com.polaris.mes.service.impl;

import com.polaris.mes.common.TenantContext;
import com.polaris.mes.service.PlatformService;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.LinkedHashMap;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.sql.Timestamp;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.time.Instant;
import java.time.temporal.ChronoUnit;
import java.util.regex.Pattern;

@Service
@Transactional
public class PlatformServiceImpl implements PlatformService {
    private static final Pattern TENANT_CODE = Pattern.compile("[a-z][a-z0-9-]{2,31}");
    private final JdbcTemplate jdbc;

    public PlatformServiceImpl(JdbcTemplate jdbc) { this.jdbc = jdbc; }

    /** Public login discovery contains no user or business data. */
    public List<Map<String, Object>> listActiveTenants() {
        return normalizedRows(jdbc.queryForList("select id, tenant_code, tenant_name, tenant_type, plan_code from sys_tenant where status=1 order by case when tenant_type='PLATFORM' then 0 else 1 end, id"));
    }

    /**
     * Creates a tenant and its first administrator in one transaction. The
     * payload intentionally contains no tenant id: the new id is generated by
     * the database and all subsequent requests are bound by the token.
     */
    @Transactional
    public Map<String, Object> registerTenant(Map<String, Object> payload, String passwordHash) {
        String tenantCode = required(payload, "tenantCode", "租户编码").toLowerCase(java.util.Locale.ROOT);
        String tenantName = required(payload, "tenantName", "企业名称");
        String username = required(payload, "username", "管理员用户名");
        String displayName = required(payload, "displayName", "管理员姓名");
        String contactName = stringOr(payload.get("contactName"), displayName);
        String contactEmail = string(payload.get("contactEmail"));
        if (!TENANT_CODE.matcher(tenantCode).matches()) {
            throw new IllegalArgumentException("租户编码需为 3-32 位小写字母、数字或短横线，且以字母开头");
        }
        if (username.length() < 3 || username.length() > 64) throw new IllegalArgumentException("管理员用户名长度必须为 3-64 位");
        if (passwordHash == null || passwordHash.isBlank()) throw new IllegalArgumentException("管理员密码不能为空");
        if (jdbc.queryForObject("select count(*) from sys_tenant where tenant_code=?", Integer.class, tenantCode) > 0) {
            throw new IllegalArgumentException("租户编码已被注册");
        }
        if (contactEmail != null && !contactEmail.isBlank() && !contactEmail.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) {
            throw new IllegalArgumentException("联系邮箱格式不正确");
        }
        try {
            jdbc.update("insert into sys_tenant(tenant_code, tenant_name, plan_code, contact_name, contact_email, trial_ends_at, max_users, status) " +
                    "values(?,?,?,?,?,?,?,1)", tenantCode, tenantName, "STARTER", contactName, contactEmail,
                    Timestamp.from(Instant.now().plus(14, ChronoUnit.DAYS)), 10);
        } catch (org.springframework.dao.DuplicateKeyException ex) {
            throw new IllegalArgumentException("租户编码已被注册");
        }
        long newTenantId = jdbc.queryForObject("select id from sys_tenant where tenant_code=?", Long.class, tenantCode);
        seedTenantRoles(newTenantId);
        try {
            jdbc.update("insert into sys_user(tenant_id, username, display_name, password_hash, status, role_code) values(?,?,?,?,1,'admin')",
                    newTenantId, username, displayName, passwordHash);
        } catch (org.springframework.dao.DuplicateKeyException ex) {
            throw new IllegalArgumentException("管理员用户名已存在");
        }
        long userId = jdbc.queryForObject("select id from sys_user where tenant_id=? and username=?", Long.class, newTenantId, username);
        seedTenantPlatformAccess(newTenantId);
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("tenantId", newTenantId);
        result.put("tenantCode", tenantCode);
        result.put("tenantName", tenantName);
        result.put("userId", userId);
        result.put("username", username);
        result.put("displayName", displayName);
        result.put("roleCode", "admin");
        return result;
    }

    private void seedTenantRoles(long tenantId) {
        List<List<String>> roles = List.of(
                List.of("admin", "系统管理员", "全量菜单、按钮、接口和字段权限"),
                List.of("planner", "计划员", "BOM、生产计划、工单与报表权限"),
                List.of("warehouse", "仓库管理员", "收发料、库存、条码、调拨与盘点权限"),
                List.of("quality", "质量管理员", "检验计划、检验批、不合格处置与质量整改"),
                List.of("operator", "现场操作员", "PDA 扫码、报工与领料权限"));
        for (List<String> role : roles) {
            jdbc.update("insert into sys_role(tenant_id, role_code, role_name, description, status) values(?,?,?,?,1)",
                    tenantId, role.get(0), role.get(1), role.get(2));
        }
        jdbc.update("insert into sys_permission(tenant_id, role_code, resource_type, resource_code, action_code, field_mask_json) values(?,?,?,?,?,?)",
                tenantId, "admin", "MENU", "*", "*", "{}");
        seedTenantMenus(tenantId);
        seedTenantDictionaries(tenantId);
        seedTenantDataSources(tenantId);
    }

    private void seedTenantMenus(long tenantId) {
        // Some lightweight installations do not enable the menu module. Tenant
        // registration must still succeed there; the full platform schema has it.
        if (!jdbc.queryForObject("select count(*) from information_schema.tables where lower(table_name)=lower(?)", Integer.class, "sys_menu").equals(1)) return;
        List<String[]> roots = List.of(
                new String[]{"dashboard", "工作台", "/dashboard", "grid", "10"},
                new String[]{"design", "设计中心", "", "layout", "80"},
                new String[]{"admin", "系统管理", "", "settings", "90"});
        for (String[] item : roots) {
            try { jdbc.update("insert into sys_menu(tenant_id,parent_id,menu_code,menu_name,menu_type,route_path,icon,sort_no,visible) values(?,?,?,?,?,?,?,?,1)", tenantId, 0, item[0], item[1], item[2].isBlank() ? "GROUP" : "MENU", item[2], item[3], Integer.parseInt(item[4])); } catch (org.springframework.dao.DuplicateKeyException ignored) {}
        }
        seedMenuChild(tenantId, "design", "reports", "快速报表", "/design/reports", "chart", 10);
        seedMenuChild(tenantId, "design", "data-sources", "数据源维护", "/design/data-sources", "database", 20);
        seedMenuChild(tenantId, "design", "low-code", "低代码页面", "/design/low-code", "layout", 30);
        seedMenuChild(tenantId, "design", "big-screen", "大屏展示", "/design/big-screen", "monitor", 40);
        seedMenuChild(tenantId, "admin", "users", "用户", "/admin/users", "users", 10);
        seedMenuChild(tenantId, "admin", "roles", "角色与权限", "/admin/roles", "shield", 20);
        seedMenuChild(tenantId, "admin", "menus", "菜单维护", "/admin/menus", "layout", 30);
        seedMenuChild(tenantId, "admin", "tenants", "租户维护", "/admin/tenants", "settings", 40);
        seedMenuChild(tenantId, "admin", "dictionaries", "字典配置", "/admin/dictionaries", "sliders", 50);
    }

    private void seedMenuChild(long tenantId, String parentCode, String code, String name, String route, String icon, int sort) {
        Long parentId = jdbc.queryForObject("select id from sys_menu where tenant_id=? and menu_code=?", Long.class, tenantId, parentCode);
        try { jdbc.update("insert into sys_menu(tenant_id,parent_id,menu_code,menu_name,menu_type,route_path,icon,sort_no,visible) values(?,?,?,?,?,?,?,?,1)", tenantId, parentId, code, name, "MENU", route, icon, sort); } catch (org.springframework.dao.DuplicateKeyException ignored) {}
    }

    private void seedTenantDictionaries(long tenantId) {
        List<String[]> values = List.of(
                new String[]{"APPROVAL_ACTION", "APPROVED", "同意", "同意", "1"}, new String[]{"APPROVAL_ACTION", "REJECTED", "驳回", "驳回", "2"},
                new String[]{"BUSINESS_STATUS", "REVIEW", "待评审", "待评审", "1"}, new String[]{"BUSINESS_STATUS", "COMPLETED", "已完成", "已完成", "9"},
                new String[]{"COMMON_STATUS", "ACTIVE", "已启用", "ACTIVE", "1"}, new String[]{"COMMON_STATUS", "INACTIVE", "已停用", "INACTIVE", "2"});
        for (String[] item : values) try { jdbc.update("insert into sys_dictionary(tenant_id,dict_type,parent_id,dict_code,dict_label,dict_value,locale,sort_no,status) values(?,?,?,?,? ,?,'zh-CN',?,1)", tenantId, item[0], 0, item[1], item[2], item[3], Integer.parseInt(item[4])); } catch (org.springframework.dao.DuplicateKeyException ignored) {}
    }

    private void seedTenantDataSources(long tenantId) {
        try { jdbc.update("insert into data_source_config(tenant_id,source_code,source_name,source_type,config_json,schema_json,status) values(?,?,?,?,?,?,1)", tenantId, "work_order", "生产工单", "TABLE", "{}", "{\"columns\":[\"status\",\"plan_qty\",\"completed_qty\"]}"); } catch (org.springframework.dao.DuplicateKeyException ignored) {}
        try { jdbc.update("insert into data_source_config(tenant_id,source_code,source_name,source_type,config_json,schema_json,status) values(?,?,?,?,?,?,1)", tenantId, "inventory", "库存明细", "TABLE", "{}", "{\"columns\":[\"material_code\",\"material_name\",\"available_qty\",\"safety_stock\"]}"); } catch (org.springframework.dao.DuplicateKeyException ignored) {}
    }

    private void seedTenantPlatformAccess(long tenantId) {
        if (!tableExists("platform_feature")) return;
        try { jdbc.update("insert into tenant_billing_account(tenant_id) values(?)", tenantId); } catch (org.springframework.dao.DataAccessException ignored) {}
        try { jdbc.update("insert into tenant_points_account(tenant_id) values(?)", tenantId); } catch (org.springframework.dao.DataAccessException ignored) {}
        try { jdbc.update("insert into tenant_traffic_account(tenant_id, quota_bytes) values(?, 1073741824)", tenantId); } catch (org.springframework.dao.DataAccessException ignored) {}
        try { jdbc.update("insert into tenant_storage_account(tenant_id, quota_bytes) values(?, 10737418240)", tenantId); } catch (org.springframework.dao.DataAccessException ignored) {}
        for (Map<String, Object> feature : jdbc.queryForList("select feature_code from platform_feature where status=1")) {
            try { jdbc.update("insert into tenant_feature_grant(tenant_id, feature_code, status, quota_json, granted_by) values(?,?,1,'{}',?)", tenantId, feature.get("feature_code"), "registration"); }
            catch (org.springframework.dao.DataAccessException ignored) {}
        }
    }

    public Map<String, Object> findUser(String tenantCode, String username) {
        List<Map<String, Object>> rows = jdbc.queryForList(
                "select u.id, u.tenant_id, u.username, u.display_name, u.password_hash, u.status, u.role_code, " +
                        "t.tenant_code, t.tenant_name from sys_user u join sys_tenant t on t.id=u.tenant_id " +
                        "where u.tenant_id=t.id and t.tenant_code=? and t.status=1 and u.username=? limit 1",
                tenantCode, username);
        return rows.isEmpty() ? null : normalizedRows(rows).get(0);
    }

    public Map<String, Object> findActiveUser(long tenantId, long userId, String username) {
        List<Map<String, Object>> rows = jdbc.queryForList(
                "select u.id, u.tenant_id, u.username, u.role_code, t.tenant_code, t.tenant_name " +
                        "from sys_user u join sys_tenant t on t.id=u.tenant_id " +
                        "where u.tenant_id=? and u.id=? and u.username=? and u.status=1 and t.status=1 limit 1",
                tenantId, userId, username);
        return rows.isEmpty() ? null : normalizedRows(rows).get(0);
    }

    public void updatePasswordHash(long tenantId, long userId, String passwordHash) {
        jdbc.update("update sys_user set password_hash=?, updated_at=current_timestamp where tenant_id=? and id=?",
                passwordHash, tenantId, userId);
    }

    public void recordLogin(long tenantId, long userId) {
        jdbc.update("update sys_user set last_login_at=current_timestamp where tenant_id=? and id=?", tenantId, userId);
    }

    public Map<String, Object> findWorkOrder(long id) {
        List<Map<String, Object>> rows = jdbc.queryForList("select id, order_no, product_code, product_name, plan_qty, completed_qty, status, work_center from work_order where tenant_id=? and id=? and deleted=0 limit 1", tenantId(), id);
        return rows.isEmpty() ? null : normalizedRows(rows).get(0);
    }

    public List<Map<String, Object>> listMenus() {
        return jdbc.queryForList("select id, parent_id, menu_code, menu_name, menu_type, route_path, icon, sort_no, visible from sys_menu where tenant_id=? and deleted=0 order by sort_no, id", tenantId());
    }

    public int insertMenu(Map<String, Object> payload) {
        required(payload, "menuCode", "菜单编码");
        required(payload, "menuName", "菜单名称");
        return jdbc.update("insert into sys_menu(tenant_id, parent_id, menu_code, menu_name, menu_type, route_path, icon, sort_no, visible) values(?,?,?,?,?,?,?,?,?)",
                tenantId(), number(payload.get("parentId"), 0), string(payload.get("menuCode")), string(payload.get("menuName")),
                stringOr(payload.get("menuType"), "MENU"), string(payload.get("routePath")), string(payload.get("icon")),
                number(payload.get("sortNo"), 99), number(payload.get("visible"), 1));
    }

    public int updateMenu(long id, Map<String, Object> payload) {
        String menuName = required(payload, "menuName", "菜单名称");
        long parentId = number(payload.get("parentId"), 0);
        if (parentId == id) throw new IllegalArgumentException("菜单不能挂载到自己下面");
        return jdbc.update("update sys_menu set parent_id=?, menu_name=?, menu_type=?, route_path=?, icon=?, sort_no=?, visible=?, updated_at=current_timestamp where tenant_id=? and id=? and deleted=0",
                parentId, menuName, stringOr(payload.get("menuType"), "MENU"), string(payload.get("routePath")), string(payload.get("icon")),
                number(payload.get("sortNo"), 99), number(payload.get("visible"), 1), tenantId(), id);
    }

    public int deleteMenu(long id) {
        Number children = jdbc.queryForObject("select count(*) from sys_menu where tenant_id=? and parent_id=? and deleted=0", Number.class, tenantId(), id);
        if (children != null && children.intValue() > 0) throw new IllegalArgumentException("请先删除或移动子菜单");
        return jdbc.update("update sys_menu set deleted=1, updated_at=current_timestamp where tenant_id=? and id=?", tenantId(), id);
    }

    public List<Map<String, Object>> listUsers() {
        return jdbc.queryForList("select id, username, display_name, status, role_code, last_login_at, created_at from sys_user where tenant_id=? order by id", tenantId());
    }

    @Transactional
    public Map<String, Object> insertUser(Map<String, Object> payload, String passwordHash) {
        String username = required(payload, "username", "用户名");
        String displayName = required(payload, "displayName", "姓名");
        String roleCode = stringOr(payload.get("roleCode"), "operator");
        if (username.length() < 3 || username.length() > 64) throw new IllegalArgumentException("用户名长度必须为 3-64 位");
        if (passwordHash == null || passwordHash.isBlank()) throw new IllegalArgumentException("密码不能为空");
        if (jdbc.queryForObject("select count(*) from sys_role where tenant_id=? and role_code=? and status=1", Integer.class, tenantId(), roleCode) == 0) {
            throw new IllegalArgumentException("角色不存在或已停用");
        }
        try {
            jdbc.update("insert into sys_user(tenant_id, username, display_name, password_hash, status, role_code) values(?,?,?,?,?,?)",
                    tenantId(), username, displayName, passwordHash, number(payload.get("status"), 1), roleCode);
        } catch (org.springframework.dao.DuplicateKeyException ex) {
            throw new IllegalArgumentException("用户名已存在");
        }
        return findUserForAdmin(jdbc.queryForObject("select id from sys_user where tenant_id=? and username=?", Long.class, tenantId(), username));
    }

    @Transactional
    public Map<String, Object> updateUser(long id, Map<String, Object> payload) {
        String displayName = required(payload, "displayName", "姓名");
        String roleCode = stringOr(payload.get("roleCode"), "operator");
        if (jdbc.queryForObject("select count(*) from sys_role where tenant_id=? and role_code=? and status=1", Integer.class, tenantId(), roleCode) == 0) {
            throw new IllegalArgumentException("角色不存在或已停用");
        }
        int updated = jdbc.update("update sys_user set display_name=?, role_code=?, status=?, updated_at=current_timestamp where tenant_id=? and id=?",
                displayName, roleCode, number(payload.get("status"), 1), tenantId(), id);
        if (updated == 0) throw new IllegalArgumentException("用户不存在");
        return findUserForAdmin(id);
    }

    @Transactional
    public Map<String, Object> updateUserPassword(long id, String passwordHash) {
        int updated = jdbc.update("update sys_user set password_hash=?, updated_at=current_timestamp where tenant_id=? and id=?",
                passwordHash, tenantId(), id);
        if (updated == 0) throw new IllegalArgumentException("用户不存在");
        return findUserForAdmin(id);
    }

    private Map<String, Object> findUserForAdmin(long id) {
        List<Map<String, Object>> rows = jdbc.queryForList("select id, username, display_name, status, role_code, last_login_at, created_at from sys_user where tenant_id=? and id=? limit 1", tenantId(), id);
        if (rows.isEmpty()) throw new IllegalArgumentException("用户不存在");
        return rows.get(0);
    }

    public List<Map<String, Object>> listRoles() {
        return jdbc.queryForList("select id, role_code, role_name, description, status from sys_role where tenant_id=? order by id", tenantId());
    }

    @Transactional
    public Map<String, Object> insertRole(Map<String, Object> payload) {
        String code = required(payload, "roleCode", "角色编码").toLowerCase(Locale.ROOT);
        String name = required(payload, "roleName", "角色名称");
        try {
            jdbc.update("insert into sys_role(tenant_id, role_code, role_name, description, status) values(?,?,?,?,?)",
                    tenantId(), code, name, string(payload.get("description")), number(payload.get("status"), 1));
        } catch (org.springframework.dao.DuplicateKeyException ex) {
            throw new IllegalArgumentException("角色编码已存在");
        }
        Long id = jdbc.queryForObject("select id from sys_role where tenant_id=? and role_code=?", Long.class, tenantId(), code);
        return findRole(id);
    }

    @Transactional
    public Map<String, Object> updateRole(long id, Map<String, Object> payload) {
        String name = required(payload, "roleName", "角色名称");
        int updated = jdbc.update("update sys_role set role_name=?, description=?, status=? where tenant_id=? and id=?",
                name, string(payload.get("description")), number(payload.get("status"), 1), tenantId(), id);
        if (updated == 0) throw new IllegalArgumentException("角色不存在");
        return findRole(id);
    }

    @Transactional
    public int deleteRole(long id) {
        Map<String, Object> role = findRole(id);
        if ("admin".equals(role.get("role_code"))) throw new IllegalArgumentException("系统管理员角色不可删除");
        Number users = jdbc.queryForObject("select count(*) from sys_user where tenant_id=? and role_code=?", Number.class, tenantId(), role.get("role_code"));
        if (users != null && users.intValue() > 0) throw new IllegalArgumentException("该角色仍被用户使用，不能删除");
        jdbc.update("delete from sys_permission where tenant_id=? and role_code=?", tenantId(), role.get("role_code"));
        return jdbc.update("delete from sys_role where tenant_id=? and id=?", tenantId(), id);
    }

    @Transactional
    public List<Map<String, Object>> updateRolePermissions(String roleCode, List<Map<String, Object>> permissions) {
        if (one("select id from sys_role where tenant_id=? and role_code=?", tenantId(), roleCode) == null) throw new IllegalArgumentException("角色不存在");
        jdbc.update("delete from sys_permission where tenant_id=? and role_code=?", tenantId(), roleCode);
        if (permissions != null) for (Map<String, Object> permission : permissions) {
            String resourceType = stringOr(permission.get("resourceType"), "MENU");
            String resourceCode = required(permission, "resourceCode", "资源编码");
            String actionCode = stringOr(permission.get("actionCode"), "VIEW");
            jdbc.update("insert into sys_permission(tenant_id, role_code, resource_type, resource_code, action_code, field_mask_json, effect) values(?,?,?,?,?,?,?)",
                    tenantId(), roleCode, resourceType, resourceCode, actionCode, stringOr(permission.get("fieldMaskJson"), "{}"), stringOr(permission.get("effect"), "ALLOW"));
        }
        return listPermissions(roleCode);
    }

    private Map<String, Object> findRole(long id) {
        Map<String, Object> role = one("select id, role_code, role_name, description, status from sys_role where tenant_id=? and id=?", tenantId(), id);
        if (role == null) throw new IllegalArgumentException("角色不存在");
        return role;
    }

    public List<Map<String, Object>> listBoms() {
        return normalizedRows(jdbc.queryForList("select b.id, b.bom_code, b.product_code, b.product_name, b.version, b.status, count(i.id) item_count from bom b left join bom_item i on i.tenant_id=b.tenant_id and i.bom_id=b.id where b.tenant_id=? and b.deleted=0 group by b.id, b.bom_code, b.product_code, b.product_name, b.version, b.status order by b.id desc", tenantId()));
    }

    @Transactional
    public int insertBom(Map<String, Object> payload) {
        String bomCode = required(payload, "bomCode", "BOM 编码");
        String productCode = required(payload, "productCode", "产品编码");
        String productName = required(payload, "productName", "产品名称");
        int updated = jdbc.update("insert into bom(tenant_id, bom_code, product_code, product_name, version, status, remark) values(?,?,?,?,?,?,?)",
                tenantId(), bomCode, productCode, productName,
                stringOr(payload.get("version"), "V1"), stringOr(payload.get("status"), "DRAFT"), string(payload.get("remark")));
        Long bomId = jdbc.queryForObject("select id from bom where tenant_id=? and bom_code=?", Long.class, tenantId(), bomCode);
        Object rawItems = payload.get("items");
        if (rawItems instanceof List<?> items) {
            for (Object rawItem : items) {
                if (!(rawItem instanceof Map<?, ?> item)) throw new IllegalArgumentException("BOM 物料明细格式不正确");
                Map<String, Object> normalized = new LinkedHashMap<>();
                item.forEach((key, value) -> normalized.put(String.valueOf(key), value));
                insertBomItemInternal(bomId, normalized);
            }
        }
        return updated;
    }

    @Override
    @Transactional(readOnly = true)
    public List<Map<String, Object>> listBomItems(long bomId) {
        findBom(bomId);
        return jdbc.queryForList("select id, bom_id, material_code, material_name, quantity, unit, loss_rate, issue_method from bom_item where tenant_id=? and bom_id=? order by id", tenantId(), bomId);
    }

    @Override
    public int publishBom(long bomId) {
        findBom(bomId);
        Number itemCount = jdbc.queryForObject("select count(*) from bom_item where tenant_id=? and bom_id=?", Number.class, tenantId(), bomId);
        if (itemCount == null || itemCount.intValue() == 0) throw new IllegalArgumentException("BOM 至少需要一条物料明细才能发布");
        int updated = jdbc.update("update bom set status='RELEASED' where tenant_id=? and id=? and deleted=0 and status<>'RELEASED'", tenantId(), bomId);
        return updated == 0 ? 1 : updated;
    }

    @Override
    @Transactional(readOnly = true)
    public Map<String, Object> calculateMrp(Map<String, Object> payload) {
        String productCode = required(payload, "productCode", "产品编码");
        int planQty = number(payload.get("planQty"), 0);
        if (planQty <= 0) throw new IllegalArgumentException("计划数量必须大于 0");
        Map<String, Object> bom = one("select id, bom_code, product_code, product_name, version, status from bom where tenant_id=? and product_code=? and status='RELEASED' and deleted=0 order by id desc limit 1", tenantId(), productCode);
        if (bom == null) throw new IllegalArgumentException("未找到产品对应的已发布 BOM");

        List<Map<String, Object>> requirements = new ArrayList<>();
        for (Map<String, Object> item : listBomItems(number(bom.get("id"), 0))) {
            BigDecimal quantityPer = decimal(item.get("quantity"), BigDecimal.ZERO);
            BigDecimal lossRate = decimal(item.get("loss_rate"), BigDecimal.ZERO);
            BigDecimal gross = quantityPer.multiply(BigDecimal.valueOf(planQty))
                    .multiply(BigDecimal.ONE.add(lossRate.divide(BigDecimal.valueOf(100), 8, RoundingMode.HALF_UP)));
            int requiredQty = gross.setScale(0, RoundingMode.CEILING).intValue();
            Map<String, Object> stock = one("select coalesce(sum(available_qty),0) available_qty, coalesce(sum(in_transit_qty),0) in_transit_qty from inventory where tenant_id=? and material_code=? and stock_status='AVAILABLE'", tenantId(), item.get("material_code"));
            int availableQty = number(stock == null ? null : stock.get("available_qty"), 0);
            int inTransitQty = number(stock == null ? null : stock.get("in_transit_qty"), 0);
            int shortageQty = Math.max(0, requiredQty - availableQty);
            Map<String, Object> requirement = new LinkedHashMap<>();
            requirement.put("materialCode", item.get("material_code"));
            requirement.put("materialName", item.get("material_name"));
            requirement.put("unit", item.get("unit"));
            requirement.put("quantityPer", quantityPer);
            requirement.put("lossRate", lossRate);
            requirement.put("requiredQty", requiredQty);
            requirement.put("availableQty", availableQty);
            requirement.put("inTransitQty", inTransitQty);
            requirement.put("shortageQty", shortageQty);
            requirement.put("suggestion", shortageQty > 0 ? "采购 / 委外" : "库存可满足");
            requirements.add(requirement);
        }
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("productCode", productCode);
        result.put("productName", bom.get("product_name"));
        result.put("planQty", planQty);
        result.put("bomCode", bom.get("bom_code"));
        result.put("bomVersion", bom.get("version"));
        result.put("materialCount", requirements.size());
        result.put("shortageCount", requirements.stream().filter(item -> number(item.get("shortageQty"), 0) > 0).count());
        result.put("shortageQty", requirements.stream().mapToInt(item -> number(item.get("shortageQty"), 0)).sum());
        result.put("requirements", requirements);
        return result;
    }

    private int insertBomItemInternal(long bomId, Map<String, Object> payload) {
        String materialCode = required(payload, "materialCode", "物料编码");
        String materialName = required(payload, "materialName", "物料名称");
        BigDecimal quantity = decimal(payload.get("quantity"), BigDecimal.ZERO);
        if (quantity.compareTo(BigDecimal.ZERO) <= 0) throw new IllegalArgumentException("BOM 用量必须大于 0");
        BigDecimal lossRate = decimal(payload.get("lossRate"), BigDecimal.ZERO);
        if (lossRate.compareTo(BigDecimal.ZERO) < 0 || lossRate.compareTo(BigDecimal.valueOf(100)) > 0) throw new IllegalArgumentException("损耗率必须在 0 到 100 之间");
        return jdbc.update("insert into bom_item(tenant_id,bom_id,material_code,material_name,quantity,unit,loss_rate,issue_method) values(?,?,?,?,?,?,?,?)",
                tenantId(), bomId, materialCode, materialName, quantity, stringOr(payload.get("unit"), "件"), lossRate, stringOr(payload.get("issueMethod"), "PICK"));
    }

    private Map<String, Object> findBom(long bomId) {
        Map<String, Object> bom = one("select id, bom_code, product_code, product_name, version, status from bom where tenant_id=? and id=? and deleted=0", tenantId(), bomId);
        if (bom == null) throw new IllegalArgumentException("BOM 不存在");
        return bom;
    }

    private Map<String, Object> one(String sql, Object... args) {
        List<Map<String, Object>> rows = jdbc.queryForList(sql, args);
        if (rows.isEmpty()) return null;
        return normalizedRows(rows).get(0);
    }

    private List<Map<String, Object>> normalizedRows(List<Map<String, Object>> rows) {
        return rows.stream().map(row -> {
            Map<String, Object> normalized = new LinkedHashMap<>();
            row.forEach((key, value) -> normalized.put(String.valueOf(key).toLowerCase(Locale.ROOT), value));
            return normalized;
        }).toList();
    }

    public List<Map<String, Object>> listWorkOrders() {
        return normalizedRows(jdbc.queryForList("select id, order_no, product_code, product_name, plan_qty, completed_qty, status, planned_start, planned_end, work_center from work_order where tenant_id=? and deleted=0 order by id desc", tenantId()));
    }

    public int insertWorkOrder(Map<String, Object> payload) {
        String orderNo = required(payload, "orderNo", "工单号");
        String productCode = required(payload, "productCode", "产品编码");
        String productName = required(payload, "productName", "产品名称");
        int planQty = number(payload.get("planQty"), 0);
        if (planQty <= 0) throw new IllegalArgumentException("计划数量必须大于 0");
        return jdbc.update("insert into work_order(tenant_id, order_no, product_code, product_name, plan_qty, completed_qty, status, planned_start, planned_end, work_center) values(?,?,?,?,?,?,?,?,?,?)",
                tenantId(), orderNo, productCode, productName,
                planQty, 0, stringOr(payload.get("status"), "PLANNED"),
                string(payload.get("plannedStart")), string(payload.get("plannedEnd")), string(payload.get("workCenter")));
    }

    public int reportWork(Long id, Map<String, Object> payload) {
        int qty = number(payload.get("quantity"), 0);
        if (qty <= 0) throw new IllegalArgumentException("报工数量必须大于 0");
        Map<String, Object> workOrder = findWorkOrder(id);
        if (workOrder == null) throw new IllegalArgumentException("工单不存在或已删除");
        int planQty = number(workOrder.get("plan_qty"), 0);
        int completedQty = number(workOrder.get("completed_qty"), 0);
        if (completedQty + qty > planQty) throw new IllegalArgumentException("报工数量不能超过工单剩余数量");
        int updated = jdbc.update("update work_order set completed_qty=completed_qty+?, status=case when completed_qty+? >= plan_qty then 'COMPLETED' else 'IN_PROGRESS' end, updated_at=current_timestamp where tenant_id=? and id=? and deleted=0 and completed_qty+? <= plan_qty",
                qty, qty, tenantId(), id, qty);
        if (updated == 0) throw new IllegalArgumentException("工单不存在或已删除");
        return updated;
    }

    public List<Map<String, Object>> listPermissions(String roleCode) {
        return jdbc.queryForList("select id, role_code, resource_type, resource_code, action_code, field_mask_json, effect from sys_permission where tenant_id=? and role_code=? order by resource_type, resource_code, action_code", tenantId(), roleCode);
    }

    public List<Map<String, Object>> listReports() {
        return jdbc.queryForList("select id, report_code, report_name, source_table, chart_type, config_json, status, updated_at from report_definition where tenant_id=? order by id", tenantId());
    }

    @Transactional
    public Map<String, Object> saveReport(Map<String, Object> payload, Long id) {
        String reportCode = required(payload, "reportCode", "报表编码");
        String reportName = required(payload, "reportName", "报表名称");
        String sourceTable = required(payload, "sourceTable", "数据源");
        String chartType = stringOr(payload.get("chartType"), "TABLE").toUpperCase();
        String configJson = stringOr(payload.get("configJson"), "{}");
        validateReportSource(sourceTable);
        try {
            if (id == null) {
                jdbc.update("insert into report_definition(tenant_id, report_code, report_name, source_table, chart_type, config_json, status) values(?,?,?,?,?,?,?)",
                        tenantId(), reportCode, reportName, sourceTable, chartType, configJson, stringOr(payload.get("status"), "DRAFT"));
                id = jdbc.queryForObject("select id from report_definition where tenant_id=? and report_code=?", Long.class, tenantId(), reportCode);
            } else {
                int updated = jdbc.update("update report_definition set report_name=?, source_table=?, chart_type=?, config_json=?, updated_at=current_timestamp where tenant_id=? and id=?",
                        reportName, sourceTable, chartType, configJson, tenantId(), id);
                if (updated == 0) throw new IllegalArgumentException("报表不存在");
            }
        } catch (org.springframework.dao.DuplicateKeyException ex) {
            throw new IllegalArgumentException("报表编码已存在");
        }
        return findReport(id);
    }

    public Map<String, Object> publishReport(long id) {
        int updated = jdbc.update("update report_definition set status='PUBLISHED', updated_at=current_timestamp where tenant_id=? and id=?", tenantId(), id);
        if (updated == 0) throw new IllegalArgumentException("报表不存在");
        return findReport(id);
    }

    public Map<String, Object> previewReport(long id) {
        Map<String, Object> report = findReport(id);
        String source = String.valueOf(report.get("source_table"));
        if ("work_order".equals(source)) {
            report.put("rows", jdbc.queryForList("select status, count(*) as total, coalesce(sum(plan_qty),0) as planned_qty, coalesce(sum(completed_qty),0) as completed_qty from work_order where tenant_id=? and deleted=0 group by status order by status", tenantId()));
        } else if ("inventory".equals(source)) {
            report.put("rows", jdbc.queryForList("select material_code, material_name, warehouse_code, location_code, batch_no, available_qty, safety_stock, unit from inventory where tenant_id=? and available_qty < safety_stock order by available_qty / nullif(safety_stock,0)", tenantId()));
        } else {
            Map<String, Object> dataSource = one("select source_name, schema_json from data_source_config where tenant_id=? and source_code=? and status=1", tenantId(), source);
            if (dataSource == null) throw new IllegalArgumentException("当前数据源不存在或已停用");
            report.put("rows", List.of());
            report.put("preview_note", "数据源“" + dataSource.get("source_name") + "”已注册；接入对应查询执行器后即可返回实时数据");
        }
        return report;
    }

    private Map<String, Object> findReport(long id) {
        List<Map<String, Object>> rows = jdbc.queryForList("select id, report_code, report_name, source_table, chart_type, config_json, status, updated_at from report_definition where tenant_id=? and id=? limit 1", tenantId(), id);
        if (rows.isEmpty()) throw new IllegalArgumentException("报表不存在");
        return rows.get(0);
    }

    private void validateReportSource(String sourceTable) {
        if (!List.of("work_order", "inventory").contains(sourceTable)
                && one("select id from data_source_config where tenant_id=? and source_code=? and status=1", tenantId(), sourceTable) == null) {
            throw new IllegalArgumentException("不允许使用该数据源");
        }
    }

    public List<Map<String, Object>> listLowCodePages() {
        return jdbc.queryForList("select id, page_code, page_name, page_type, schema_json, status, updated_at from lowcode_page where tenant_id=? order by id", tenantId());
    }

    @Transactional
    public Map<String, Object> saveLowCodePage(Map<String, Object> payload, Long id) {
        String pageCode = required(payload, "pageCode", "页面编码");
        String pageName = required(payload, "pageName", "页面名称");
        String pageType = stringOr(payload.get("pageType"), "FORM");
        String schemaJson = stringOr(payload.get("schemaJson"), "{\"fields\":[]}");
        if (!schemaJson.trim().startsWith("{")) throw new IllegalArgumentException("页面 schema 必须是 JSON 对象");
        try {
            if (id == null) {
                jdbc.update("insert into lowcode_page(tenant_id, page_code, page_name, page_type, schema_json, status) values(?,?,?,?,?,?)",
                        tenantId(), pageCode, pageName, pageType, schemaJson, "DRAFT");
                id = jdbc.queryForObject("select id from lowcode_page where tenant_id=? and page_code=?", Long.class, tenantId(), pageCode);
            } else {
                int updated = jdbc.update("update lowcode_page set page_name=?, page_type=?, schema_json=?, updated_at=current_timestamp where tenant_id=? and id=?",
                        pageName, pageType, schemaJson, tenantId(), id);
                if (updated == 0) throw new IllegalArgumentException("页面不存在");
            }
        } catch (org.springframework.dao.DuplicateKeyException ex) {
            throw new IllegalArgumentException("页面编码已存在");
        }
        return findLowCodePage(id);
    }

    public Map<String, Object> publishLowCodePage(long id) {
        int updated = jdbc.update("update lowcode_page set status='PUBLISHED', updated_at=current_timestamp where tenant_id=? and id=?", tenantId(), id);
        if (updated == 0) throw new IllegalArgumentException("页面不存在");
        return findLowCodePage(id);
    }

    private Map<String, Object> findLowCodePage(long id) {
        List<Map<String, Object>> rows = jdbc.queryForList("select id, page_code, page_name, page_type, schema_json, status, updated_at from lowcode_page where tenant_id=? and id=? limit 1", tenantId(), id);
        if (rows.isEmpty()) throw new IllegalArgumentException("页面不存在");
        return rows.get(0);
    }

    public List<Map<String, Object>> listDashboards() {
        return jdbc.queryForList("select id, dashboard_code, dashboard_name, layout_json, theme, status, updated_at from dashboard_config where tenant_id=? order by id", tenantId());
    }

    @Transactional
    public Map<String, Object> saveDashboard(Map<String, Object> payload, Long id) {
        String code = required(payload, "dashboardCode", "大屏编码");
        String name = required(payload, "dashboardName", "大屏名称");
        String layout = stringOr(payload.get("layoutJson"), "{\"widgets\":[]}");
        if (!layout.trim().startsWith("{")) throw new IllegalArgumentException("大屏布局必须是 JSON 对象");
        try {
            if (id == null) {
                jdbc.update("insert into dashboard_config(tenant_id, dashboard_code, dashboard_name, layout_json, theme, status) values(?,?,?,?,?,?)",
                        tenantId(), code, name, layout, stringOr(payload.get("theme"), "dark-blue"), "DRAFT");
                id = jdbc.queryForObject("select id from dashboard_config where tenant_id=? and dashboard_code=?", Long.class, tenantId(), code);
            } else {
                int updated = jdbc.update("update dashboard_config set dashboard_name=?, layout_json=?, theme=?, updated_at=current_timestamp where tenant_id=? and id=?",
                        name, layout, stringOr(payload.get("theme"), "dark-blue"), tenantId(), id);
                if (updated == 0) throw new IllegalArgumentException("大屏不存在");
            }
        } catch (org.springframework.dao.DuplicateKeyException ex) {
            throw new IllegalArgumentException("大屏编码已存在");
        }
        return findDashboard(id);
    }

    public Map<String, Object> publishDashboard(long id) {
        int updated = jdbc.update("update dashboard_config set status='PUBLISHED', updated_at=current_timestamp where tenant_id=? and id=?", tenantId(), id);
        if (updated == 0) throw new IllegalArgumentException("大屏不存在");
        return findDashboard(id);
    }

    private Map<String, Object> findDashboard(long id) {
        Map<String, Object> dashboard = one("select id, dashboard_code, dashboard_name, layout_json, theme, status, updated_at from dashboard_config where tenant_id=? and id=?", tenantId(), id);
        if (dashboard == null) throw new IllegalArgumentException("大屏不存在");
        return dashboard;
    }

    public List<Map<String, Object>> listDataSources() {
        return normalizedRows(jdbc.queryForList("select id, source_code, source_name, source_type, config_json, schema_json, status, updated_at from data_source_config where tenant_id=? order by id", tenantId()))
                .stream().map(row -> {
                    Map<String, Object> result = new LinkedHashMap<>(row);
                    result.remove("config_json");
                    result.put("configJson", row.get("config_json"));
                    result.put("schemaJson", row.get("schema_json"));
                    result.put("enabled", number(row.get("status"), 0) == 1);
                    return result;
                }).toList();
    }

    @Transactional
    public Map<String, Object> saveDataSource(Map<String, Object> payload, Long id) {
        String code = required(payload, "sourceCode", "数据源编码");
        String name = required(payload, "sourceName", "数据源名称");
        String config = stringOr(payload.get("configJson"), "{}");
        String schema = stringOr(payload.get("schemaJson"), "{}");
        if (!config.trim().startsWith("{") || !schema.trim().startsWith("{")) throw new IllegalArgumentException("数据源配置必须是 JSON 对象");
        try {
            if (id == null) {
                jdbc.update("insert into data_source_config(tenant_id, source_code, source_name, source_type, config_json, schema_json, status) values(?,?,?,?,?,?,?)",
                        tenantId(), code, name, stringOr(payload.get("sourceType"), "SQL"), config, schema, number(payload.get("status"), 1));
                id = jdbc.queryForObject("select id from data_source_config where tenant_id=? and source_code=?", Long.class, tenantId(), code);
            } else {
                int updated = jdbc.update("update data_source_config set source_name=?, source_type=?, config_json=?, schema_json=?, status=?, updated_at=current_timestamp where tenant_id=? and id=?",
                        name, stringOr(payload.get("sourceType"), "SQL"), config, schema, number(payload.get("status"), 1), tenantId(), id);
                if (updated == 0) throw new IllegalArgumentException("数据源不存在");
            }
        } catch (org.springframework.dao.DuplicateKeyException ex) {
            throw new IllegalArgumentException("数据源编码已存在");
        }
        Map<String, Object> source = one("select id, source_code, source_name, source_type, config_json, schema_json, status, updated_at from data_source_config where tenant_id=? and id=?", tenantId(), id);
        source.put("enabled", number(source.get("status"), 0) == 1);
        return source;
    }

    public Map<String, Object> toggleDataSource(long id, boolean enabled) {
        int updated = jdbc.update("update data_source_config set status=?, updated_at=current_timestamp where tenant_id=? and id=?", enabled ? 1 : 0, tenantId(), id);
        if (updated == 0) throw new IllegalArgumentException("数据源不存在");
        Map<String, Object> source = one("select id, source_code, source_name, source_type, config_json, schema_json, status, updated_at from data_source_config where tenant_id=? and id=?", tenantId(), id);
        source.put("enabled", enabled);
        return source;
    }

    public Map<String, Object> overview() {
        long tenant = tenantId();
        Map<String, Object> data = new LinkedHashMap<>();
        data.put("workOrders", scalar("select count(*) from work_order where tenant_id=? and deleted=0", tenant));
        data.put("inProgressOrders", scalar("select count(*) from work_order where tenant_id=? and status='IN_PROGRESS' and deleted=0", tenant));
        data.put("completedOrders", scalar("select count(*) from work_order where tenant_id=? and status='COMPLETED' and deleted=0", tenant));
        data.put("plannedOrders", scalar("select count(*) from work_order where tenant_id=? and status='PLANNED' and deleted=0", tenant));
        data.put("inventorySkus", scalar("select count(distinct material_code) from inventory where tenant_id=?", tenant));
        data.put("lowStock", scalar("select count(*) from inventory where tenant_id=? and available_qty < safety_stock", tenant));
        data.put("todayTransactions", scalar("select count(*) from material_transaction where tenant_id=? and date(created_at)=current_date", tenant));
        data.put("completedQty", scalar("select coalesce(sum(completed_qty),0) from work_order where tenant_id=? and deleted=0", tenant));
        data.put("trend", jdbc.queryForList("select date(planned_start) as day, coalesce(sum(plan_qty),0) as planned, coalesce(sum(completed_qty),0) as actual from work_order where tenant_id=? and deleted=0 and planned_start >= current_date - interval 6 day group by date(planned_start) order by day", tenant));
        data.put("alerts", jdbc.queryForList("select material_code as code, material_name as name, concat(warehouse_code, ' / ', location_code) as warehouse, available_qty as qty, safety_stock as safe, unit, case when safety_stock > 0 then round(available_qty * 100 / safety_stock) else 0 end as percent from inventory where tenant_id=? and available_qty < safety_stock order by available_qty / nullif(safety_stock, 0)", tenant));
        data.put("events", jdbc.queryForList("select operator_name as actor, transaction_type as type, material_code, quantity, unit, date_format(created_at, '%H:%i') as time from material_transaction where tenant_id=? order by created_at desc, id desc limit 4", tenant));
        return data;
    }

    public Map<String, Object> tenantProfile() {
        List<Map<String, Object>> rows = jdbc.queryForList("select id, tenant_code, tenant_name, tenant_type, plan_code, contact_name, contact_email, trial_ends_at, max_users, status, created_at from sys_tenant where id=? limit 1", tenantId());
        if (rows.isEmpty()) throw new IllegalArgumentException("租户不存在");
        Map<String, Object> profile = new LinkedHashMap<>(rows.get(0));
        profile.put("user_count", scalar("select count(*) from sys_user where tenant_id=?", tenantId()));
        profile.put("tenantCode", profile.get("tenant_code"));
        profile.put("tenantName", profile.get("tenant_name"));
        profile.put("tenantType", profile.get("tenant_type"));
        profile.put("planCode", profile.get("plan_code"));
        profile.put("contactName", profile.get("contact_name"));
        profile.put("contactEmail", profile.get("contact_email"));
        profile.put("trialEndsAt", profile.get("trial_ends_at"));
        profile.put("maxUsers", profile.get("max_users"));
        profile.put("userCount", profile.get("user_count"));
        return profile;
    }

    @Transactional
    public Map<String, Object> updateTenantProfile(Map<String, Object> payload) {
        String name = required(payload, "tenantName", "企业名称");
        String email = string(payload.get("contactEmail"));
        if (email != null && !email.isBlank() && !email.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) throw new IllegalArgumentException("联系邮箱格式不正确");
        int updated = jdbc.update("update sys_tenant set tenant_name=?, contact_name=?, contact_email=?, max_users=?, plan_code=?, updated_at=current_timestamp where id=?",
                name, string(payload.get("contactName")), email, Math.max(1, number(payload.get("maxUsers"), 10)), stringOr(payload.get("planCode"), "STARTER"), tenantId());
        if (updated == 0) throw new IllegalArgumentException("租户不存在");
        return tenantProfile();
    }

    private Object scalar(String sql, Object... args) { return jdbc.queryForObject(sql, Object.class, args); }
    private boolean tableExists(String table) {
        Integer count = jdbc.queryForObject("select count(*) from information_schema.tables where lower(table_name)=lower(?)", Integer.class, table);
        return count != null && count > 0;
    }
    private long tenantId() { return TenantContext.require().tenantId(); }
    private static String required(Map<String, Object> payload, String key, String label) {
        String value = string(payload.get(key));
        if (value == null || value.isBlank()) throw new IllegalArgumentException(label + "不能为空");
        return value;
    }
    private static String string(Object value) { return value == null ? null : String.valueOf(value); }
    private static String stringOr(Object value, String fallback) { String text = string(value); return text == null || text.isBlank() ? fallback : text; }
    private static int number(Object value, int fallback) {
        if (value == null) return fallback;
        try { return Integer.parseInt(String.valueOf(value)); } catch (NumberFormatException ex) { return fallback; }
    }
    private static BigDecimal decimal(Object value, BigDecimal fallback) {
        if (value == null) return fallback;
        try { return new BigDecimal(String.valueOf(value)); } catch (NumberFormatException ex) { return fallback; }
    }
}
